export default [
  {
    character: 'NUL',
    entityName: '',
    entityNumber: '&#0;',
    description: 'Null char',
  },
  {
    character: 'SOH',
    entityName: '',
    entityNumber: '&#1;',
    description: 'Start of heading',
  },
  {
    character: 'STX',
    entityName: '',
    entityNumber: '&#2;',
    description: 'Start of text',
  },
  {
    character: 'ETX',
    entityName: '',
    entityNumber: '&#3;',
    description: 'End of text',
  },
  {
    character: 'EOT',
    entityName: '',
    entityNumber: '&#4;',
    description: 'End of transmission',
  },
  {
    character: 'ENQ',
    entityName: '',
    entityNumber: '&#5;',
    description: 'Enquiry',
  },
  {
    character: 'ACK',
    entityName: '',
    entityNumber: '&#6;',
    description: 'Acknowledgment',
  },
  {
    character: 'BEL',
    entityName: '',
    entityNumber: '&#7;',
    description: 'Bell',
  },
  {
    character: 'BS',
    entityName: '',
    entityNumber: '&#8;',
    description: 'Backspace',
  },
  {
    character: 'TAB',
    entityName: '',
    entityNumber: '&#9;',
    description: 'Horizontal tab',
  },
  {
    character: 'LF',
    entityName: '',
    entityNumber: '&#10;',
    description: 'Line feed',
  },
  {
    character: 'VT',
    entityName: '',
    entityNumber: '&#11;',
    description: 'Vertical tab',
  },
  {
    character: 'FF',
    entityName: '',
    entityNumber: '&#12;',
    description: 'Form feed',
  },
  {
    character: 'CR',
    entityName: '',
    entityNumber: '&#13;',
    description: 'Carriage return',
  },
  {
    character: 'SO',
    entityName: '',
    entityNumber: '&#14;',
    description: 'Shift out / x-on',
  },
  {
    character: 'SI',
    entityName: '',
    entityNumber: '&#15;',
    description: 'Shift in / x-off',
  },
  {
    character: 'DLE',
    entityName: '',
    entityNumber: '&#16;',
    description: 'Data line escape',
  },
  {
    character: 'DC1',
    entityName: '',
    entityNumber: '&#17;',
    description: 'Device control 1 (oft. xon)',
  },
  {
    character: 'DC2',
    entityName: '',
    entityNumber: '&#18;',
    description: 'Device control 2',
  },
  {
    character: 'DC3',
    entityName: '',
    entityNumber: '&#19;',
    description: 'Device control 3 (oft. xoff)',
  },
  {
    character: 'DC4',
    entityName: '',
    entityNumber: '&#20;',
    description: 'Device control 4',
  },
  {
    character: 'NAK',
    entityName: '',
    entityNumber: '&#21;',
    description: 'Negative acknowledgement',
  },
  {
    character: 'SYN',
    entityName: '',
    entityNumber: '&#22;',
    description: 'Synchronous idle',
  },
  {
    character: 'ETB',
    entityName: '',
    entityNumber: '&#23;',
    description: 'End of transmit block',
  },
  {
    character: 'CAN',
    entityName: '',
    entityNumber: '&#24;',
    description: 'Cancel',
  },
  {
    character: 'EM',
    entityName: '',
    entityNumber: '&#25;',
    description: 'End of medium',
  },
  {
    character: 'SUB',
    entityName: '',
    entityNumber: '&#26;',
    description: 'Substitute',
  },
  {
    character: 'ESC',
    entityName: '',
    entityNumber: '&#27;',
    description: 'Escape',
  },
  {
    character: 'FS',
    entityName: '',
    entityNumber: '&#28;',
    description: 'File separator',
  },
  {
    character: 'GS',
    entityName: '',
    entityNumber: '&#29;',
    description: 'Group separator',
  },
  {
    character: 'RS',
    entityName: '',
    entityNumber: '&#30;',
    description: 'Record separator',
  },
  {
    character: 'US',
    entityName: '',
    entityNumber: '&#31;',
    description: 'Unit separator',
  },
  {
    character: '',
    entityName: '',
    entityNumber: '&#32;',
    description: 'Space',
  },
  {
    character: '!',
    entityName: '',
    entityNumber: '&#33;',
    description: 'Exclamation mark',
  },
  {
    character: '',
    entityName: '',
    entityNumber: '&#34;',
    description: 'Quotation mark',
  },
  {
    character: '#',
    entityName: '',
    entityNumber: '&#35;',
    description: 'Number sign',
  },
  {
    character: '$',
    entityName: '',
    entityNumber: '&#36;',
    description: 'Dollar sign',
  },
  {
    character: '%',
    entityName: '',
    entityNumber: '&#37;',
    description: 'Percent sign',
  },
  {
    character: '&',
    entityName: '&amp;',
    entityNumber: '&#38;',
    description: 'Ampersand',
  },
  {
    character: "'",
    entityName: '',
    entityNumber: '&#39;',
    description: 'Apostrophe',
  },
  {
    character: '(',
    entityName: '',
    entityNumber: '&#40;',
    description: 'Opening/Left Parenthesis',
  },
  {
    character: ')',
    entityName: '',
    entityNumber: '&#41;',
    description: 'Closing/Right Parenthesis',
  },
  {
    character: '*',
    entityName: '',
    entityNumber: '&#42;',
    description: 'Asterisk',
  },
  {
    character: '+',
    entityName: '',
    entityNumber: '&#43;',
    description: 'Plus sign',
  },
  {
    character: ',',
    entityName: '',
    entityNumber: '&#44;',
    description: 'Comma',
  },
  {
    character: '-',
    entityName: '',
    entityNumber: '&#45;',
    description: 'Hyphen',
  },
  {
    character: '.',
    entityName: '',
    entityNumber: '&#46;',
    description: 'Period',
  },
  {
    character: '/',
    entityName: '',
    entityNumber: '&#47;',
    description: 'Slash',
  },
  {
    character: 0,
    entityName: '',
    entityNumber: '&#48;',
    description: 'Digit 0',
  },
  {
    character: 1,
    entityName: '',
    entityNumber: '&#49;',
    description: 'Digit 1',
  },
  {
    character: 2,
    entityName: '',
    entityNumber: '&#50;',
    description: 'Digit 2',
  },
  {
    character: 3,
    entityName: '',
    entityNumber: '&#51;',
    description: 'Digit 3',
  },
  {
    character: 4,
    entityName: '',
    entityNumber: '&#52;',
    description: 'Digit 4',
  },
  {
    character: 5,
    entityName: '',
    entityNumber: '&#53;',
    description: 'Digit 5',
  },
  {
    character: 6,
    entityName: '',
    entityNumber: '&#54;',
    description: 'Digit 6',
  },
  {
    character: 7,
    entityName: '',
    entityNumber: '&#55;',
    description: 'Digit 7',
  },
  {
    character: 8,
    entityName: '',
    entityNumber: '&#56;',
    description: 'Digit 8',
  },
  {
    character: 9,
    entityName: '',
    entityNumber: '&#57;',
    description: 'Digit 9',
  },
  {
    character: ':',
    entityName: '',
    entityNumber: '&#58;',
    description: 'Colon',
  },
  {
    character: ';',
    entityName: '',
    entityNumber: '&#59;',
    description: 'Semicolon',
  },
  {
    character: '<',
    entityName: '&lt;',
    entityNumber: '&#60;',
    description: 'Less-than',
  },
  {
    character: '=',
    entityName: '',
    entityNumber: '&#61;',
    description: 'Equals sign',
  },
  {
    character: '>',
    entityName: '&gt;',
    entityNumber: '&#62;',
    description: 'Greater than',
  },
  {
    character: '?',
    entityName: '',
    entityNumber: '&#63;',
    description: 'Question mark',
  },
  {
    character: '@',
    entityName: '',
    entityNumber: '&#64;',
    description: 'At sign',
  },
  {
    character: 'A',
    entityName: '',
    entityNumber: '&#65;',
    description: 'Uppercase A',
  },
  {
    character: 'B',
    entityName: '',
    entityNumber: '&#66;',
    description: 'Uppercase B',
  },
  {
    character: 'C',
    entityName: '',
    entityNumber: '&#67;',
    description: 'Uppercase C',
  },
  {
    character: 'D',
    entityName: '',
    entityNumber: '&#68;',
    description: 'Uppercase D',
  },
  {
    character: 'E',
    entityName: '',
    entityNumber: '&#69;',
    description: 'Uppercase E',
  },
  {
    character: 'F',
    entityName: '',
    entityNumber: '&#70;',
    description: 'Uppercase F',
  },
  {
    character: 'G',
    entityName: '',
    entityNumber: '&#71;',
    description: 'Uppercase G',
  },
  {
    character: 'H',
    entityName: '',
    entityNumber: '&#72;',
    description: 'Uppercase H',
  },
  {
    character: 'I',
    entityName: '',
    entityNumber: '&#73;',
    description: 'Uppercase I',
  },
  {
    character: 'J',
    entityName: '',
    entityNumber: '&#74;',
    description: 'Uppercase J',
  },
  {
    character: 'K',
    entityName: '',
    entityNumber: '&#75;',
    description: 'Uppercase K',
  },
  {
    character: 'L',
    entityName: '',
    entityNumber: '&#76;',
    description: 'Uppercase L',
  },
  {
    character: 'M',
    entityName: '',
    entityNumber: '&#77;',
    description: 'Uppercase M',
  },
  {
    character: 'N',
    entityName: '',
    entityNumber: '&#78;',
    description: 'Uppercase N',
  },
  {
    character: 'O',
    entityName: '',
    entityNumber: '&#79;',
    description: 'Uppercase O',
  },
  {
    character: 'P',
    entityName: '',
    entityNumber: '&#80;',
    description: 'Uppercase P',
  },
  {
    character: 'Q',
    entityName: '',
    entityNumber: '&#81;',
    description: 'Uppercase Q',
  },
  {
    character: 'R',
    entityName: '',
    entityNumber: '&#82;',
    description: 'Uppercase R',
  },
  {
    character: 'S',
    entityName: '',
    entityNumber: '&#83;',
    description: 'Uppercase S',
  },
  {
    character: 'T',
    entityName: '',
    entityNumber: '&#84;',
    description: 'Uppercase T',
  },
  {
    character: 'U',
    entityName: '',
    entityNumber: '&#85;',
    description: 'Uppercase U',
  },
  {
    character: 'V',
    entityName: '',
    entityNumber: '&#86;',
    description: 'Uppercase V',
  },
  {
    character: 'W',
    entityName: '',
    entityNumber: '&#87;',
    description: 'Uppercase W',
  },
  {
    character: 'X',
    entityName: '',
    entityNumber: '&#88;',
    description: 'Uppercase X',
  },
  {
    character: 'Y',
    entityName: '',
    entityNumber: '&#89;',
    description: 'Uppercase Y',
  },
  {
    character: 'Z',
    entityName: '',
    entityNumber: '&#90;',
    description: 'Uppercase Z',
  },
  {
    character: '[',
    entityName: '',
    entityNumber: '&#91;',
    description: 'Opening/Left square bracket',
  },
  {
    character: '\\',
    entityName: '',
    entityNumber: '&#92;',
    description: 'Backslash',
  },
  {
    character: ']',
    entityName: '',
    entityNumber: '&#93;',
    description: 'Closing/Right square bracket',
  },
  {
    character: '^',
    entityName: '',
    entityNumber: '&#94;',
    description: 'Caret',
  },
  {
    character: '_',
    entityName: '',
    entityNumber: '&#95;',
    description: 'Underscore',
  },
  {
    character: '`',
    entityName: '',
    entityNumber: '&#96;',
    description: 'Grave accent',
  },
  {
    character: 'a',
    entityName: '',
    entityNumber: '&#97;',
    description: 'Lowercase a',
  },
  {
    character: 'b',
    entityName: '',
    entityNumber: '&#98;',
    description: 'Lowercase b',
  },
  {
    character: 'c',
    entityName: '',
    entityNumber: '&#99;',
    description: 'Lowercase c',
  },
  {
    character: 'd',
    entityName: '',
    entityNumber: '&#100;',
    description: 'Lowercase d',
  },
  {
    character: 'e',
    entityName: '',
    entityNumber: '&#101;',
    description: 'Lowercase e',
  },
  {
    character: 'f',
    entityName: '',
    entityNumber: '&#102;',
    description: 'Lowercase f',
  },
  {
    character: 'g',
    entityName: '',
    entityNumber: '&#103;',
    description: 'Lowercase g',
  },
  {
    character: 'h',
    entityName: '',
    entityNumber: '&#104;',
    description: 'Lowercase h',
  },
  {
    character: 'i',
    entityName: '',
    entityNumber: '&#105;',
    description: 'Lowercase i',
  },
  {
    character: 'j',
    entityName: '',
    entityNumber: '&#106;',
    description: 'Lowercase j',
  },
  {
    character: 'k',
    entityName: '',
    entityNumber: '&#107;',
    description: 'Lowercase k',
  },
  {
    character: 'l',
    entityName: '',
    entityNumber: '&#108;',
    description: 'Lowercase l',
  },
  {
    character: 'm',
    entityName: '',
    entityNumber: '&#109;',
    description: 'Lowercase m',
  },
  {
    character: 'n',
    entityName: '',
    entityNumber: '&#110;',
    description: 'Lowercase n',
  },
  {
    character: 'o',
    entityName: '',
    entityNumber: '&#111;',
    description: 'Lowercase o',
  },
  {
    character: 'p',
    entityName: '',
    entityNumber: '&#112;',
    description: 'Lowercase p',
  },
  {
    character: 'q',
    entityName: '',
    entityNumber: '&#113;',
    description: 'Lowercase q',
  },
  {
    character: 'r',
    entityName: '',
    entityNumber: '&#114;',
    description: 'Lowercase r',
  },
  {
    character: 's',
    entityName: '',
    entityNumber: '&#115;',
    description: 'Lowercase s',
  },
  {
    character: 't',
    entityName: '',
    entityNumber: '&#116;',
    description: 'Lowercase t',
  },
  {
    character: 'u',
    entityName: '',
    entityNumber: '&#117;',
    description: 'Lowercase u',
  },
  {
    character: 'v',
    entityName: '',
    entityNumber: '&#118;',
    description: 'Lowercase v',
  },
  {
    character: 'w',
    entityName: '',
    entityNumber: '&#119;',
    description: 'Lowercase w',
  },
  {
    character: 'x',
    entityName: '',
    entityNumber: '&#120;',
    description: 'Lowercase x',
  },
  {
    character: 'y',
    entityName: '',
    entityNumber: '&#121;',
    description: 'Lowercase y',
  },
  {
    character: 'z',
    entityName: '',
    entityNumber: '&#122;',
    description: 'Lowercase z',
  },
  {
    character: '{',
    entityName: '',
    entityNumber: '&#123;',
    description: 'Opening/Left curly brace',
  },
  {
    character: '|',
    entityName: '',
    entityNumber: '&#124;',
    description: 'Vertical bar',
  },
  {
    character: '}',
    entityName: '',
    entityNumber: '&#125;',
    description: 'Closing/Right curly brace',
  },
  {
    character: '~',
    entityName: '',
    entityNumber: '&#126;',
    description: 'Tilde',
  },
  {
    character: 'À',
    entityName: '&Agrave;',
    entityNumber: '&#192;',
    description: 'Capital a with grave accent',
  },
  {
    character: 'Á',
    entityName: '&Aacute;',
    entityNumber: '&#193;',
    description: 'Capital a with acute accent',
  },
  {
    character: 'Â',
    entityName: '&Acirc;',
    entityNumber: '&#194;',
    description: 'Capital a with circumflex accent',
  },
  {
    character: 'Ã',
    entityName: '&Atilde;',
    entityNumber: '&#195;',
    description: 'Capital a with tilde',
  },
  {
    character: 'Ä',
    entityName: '&Auml;',
    entityNumber: '&#196;',
    description: 'Capital a with umlaut',
  },
  {
    character: 'Å',
    entityName: '&Aring;',
    entityNumber: '&#197;',
    description: 'Capital a with ring',
  },
  {
    character: 'Æ',
    entityName: '&AElig;',
    entityNumber: '&#198;',
    description: 'Capital ae',
  },
  {
    character: 'Ç',
    entityName: '&Ccedil;',
    entityNumber: '&#199;',
    description: 'Capital c with cedilla',
  },
  {
    character: 'È',
    entityName: '&Egrave;',
    entityNumber: '&#200;',
    description: 'Capital e with grave accent',
  },
  {
    character: 'É',
    entityName: '&Eacute;',
    entityNumber: '&#201;',
    description: 'Capital e with acute accent',
  },
  {
    character: 'Ê',
    entityName: '&Ecirc;',
    entityNumber: '&#202;',
    description: 'Capital e with circumflex accent',
  },
  {
    character: 'Ë',
    entityName: '&Euml;',
    entityNumber: '&#203;',
    description: 'Capital e with umlaut',
  },
  {
    character: 'Ì',
    entityName: '&Igrave;',
    entityNumber: '&#204;',
    description: 'Capital i with grave accent',
  },
  {
    character: 'Í',
    entityName: '&Iacute;',
    entityNumber: '&#205;',
    description: 'Capital i with accute accent',
  },
  {
    character: 'Î',
    entityName: '&Icirc;',
    entityNumber: '&#206;',
    description: 'Capital i with circumflex accent',
  },
  {
    character: 'Ï',
    entityName: '&Iuml;',
    entityNumber: '&#207;',
    description: 'Capital i with umlaut',
  },
  {
    character: 'Ð',
    entityName: '&ETH;',
    entityNumber: '&#208;',
    description: 'Capital eth (Icelandic)',
  },
  {
    character: 'Ñ',
    entityName: '&Ntilde;',
    entityNumber: '&#209;',
    description: 'Capital n with tilde',
  },
  {
    character: 'Ò',
    entityName: '&Ograve;',
    entityNumber: '&#210;',
    description: 'Capital o with grave accent',
  },
  {
    character: 'Ó',
    entityName: '&Oacute;',
    entityNumber: '&#211;',
    description: 'Capital o with accute accent',
  },
  {
    character: 'Ô',
    entityName: '&Ocirc;',
    entityNumber: '&#212;',
    description: 'Capital o with circumflex accent',
  },
  {
    character: 'Õ',
    entityName: '&Otilde;',
    entityNumber: '&#213;',
    description: 'Capital o with tilde',
  },
  {
    character: 'Ö',
    entityName: '&Ouml;',
    entityNumber: '&#214;',
    description: 'Capital o with umlaut',
  },
  {
    character: 'Ø',
    entityName: '&Oslash;',
    entityNumber: '&#216;',
    description: 'Capital o with slash',
  },
  {
    character: 'Ù',
    entityName: '&Ugrave;',
    entityNumber: '&#217;',
    description: 'Capital u with grave accent',
  },
  {
    character: 'Ú',
    entityName: '&Uacute;',
    entityNumber: '&#218;',
    description: 'Capital u with acute accent',
  },
  {
    character: 'Û',
    entityName: '&Ucirc;',
    entityNumber: '&#219;',
    description: 'Capital u with circumflex accent',
  },
  {
    character: 'Ü',
    entityName: '&Uuml;',
    entityNumber: '&#220;',
    description: 'Capital u with umlaut',
  },
  {
    character: 'Ý',
    entityName: '&Yacute;',
    entityNumber: '&#221;',
    description: 'Capital y with acute accent',
  },
  {
    character: 'Þ',
    entityName: '&THORN;',
    entityNumber: '&#222;',
    description: 'Capital thorn (Icelandic)',
  },
  {
    character: 'ß',
    entityName: '&szlig;',
    entityNumber: '&#223;',
    description: 'Lowercase sharp s (German)',
  },
  {
    character: 'à',
    entityName: '&agrave;',
    entityNumber: '&#224;',
    description: 'Lowercase a with grave accent',
  },
  {
    character: 'á',
    entityName: '&aacute;',
    entityNumber: '&#225;',
    description: 'Lowercase a with acute accent',
  },
  {
    character: 'â',
    entityName: '&acirc;',
    entityNumber: '&#226;',
    description: 'Lowercase a with circumflex accent',
  },
  {
    character: 'ã',
    entityName: '&atilde;',
    entityNumber: '&#227;',
    description: 'Lowercase a with tilde',
  },
  {
    character: 'ä',
    entityName: '&auml;',
    entityNumber: '&#228;',
    description: 'Lowercase a with umlaut',
  },
  {
    character: 'å',
    entityName: '&aring;',
    entityNumber: '&#229;',
    description: 'Lowercase a with ring',
  },
  {
    character: 'æ',
    entityName: '&aelig;',
    entityNumber: '&#230;',
    description: 'Lowercase ae',
  },
  {
    character: 'ç',
    entityName: '&ccedil;',
    entityNumber: '&#231;',
    description: 'Lowercase c with cedilla',
  },
  {
    character: 'è',
    entityName: '&egrave;',
    entityNumber: '&#232;',
    description: 'Lowercase e with grave accent',
  },
  {
    character: 'é',
    entityName: '&eacute;',
    entityNumber: '&#233;',
    description: 'Lowercase e with acute accent',
  },
  {
    character: 'ê',
    entityName: '&ecirc;',
    entityNumber: '&#234;',
    description: 'Lowercase e with circumflex accent',
  },
  {
    character: 'ë',
    entityName: '&euml;',
    entityNumber: '&#235;',
    description: 'Lowercase e with umlaut',
  },
  {
    character: 'ì',
    entityName: '&igrave;',
    entityNumber: '&#236;',
    description: 'Lowercase i with grave accent',
  },
  {
    character: 'í',
    entityName: '&iacute;',
    entityNumber: '&#237;',
    description: 'Lowercase i with acute accent',
  },
  {
    character: 'î',
    entityName: '&icirc;',
    entityNumber: '&#238;',
    description: 'Lowercase i with circumflex accent',
  },
  {
    character: 'ï',
    entityName: '&iuml;',
    entityNumber: '&#239;',
    description: 'Lowercase i with umlaut',
  },
  {
    character: 'ð',
    entityName: '&eth;',
    entityNumber: '&#240;',
    description: 'Lowercase eth (Icelandic)',
  },
  {
    character: 'ñ',
    entityName: '&ntilde;',
    entityNumber: '&#241;',
    description: 'Lowercase n with tilde',
  },
  {
    character: 'ò',
    entityName: '&ograve;',
    entityNumber: '&#242;',
    description: 'Lowercase o with grave accent',
  },
  {
    character: 'ó',
    entityName: '&oacute;',
    entityNumber: '&#243;',
    description: 'Lowercase o with acute accent',
  },
  {
    character: 'ô',
    entityName: '&ocirc;',
    entityNumber: '&#244;',
    description: 'Lowercase o with circumflex accent',
  },
  {
    character: 'õ',
    entityName: '&otilde;',
    entityNumber: '&#245;',
    description: 'Lowercase o with tilde',
  },
  {
    character: 'ö',
    entityName: '&ouml;',
    entityNumber: '&#246;',
    description: 'Lowercase o with umlaut',
  },
  {
    character: 'ø',
    entityName: '&oslash;',
    entityNumber: '&#248;',
    description: 'Lowercase o with slash',
  },
  {
    character: 'ù',
    entityName: '&ugrave;',
    entityNumber: '&#249;',
    description: 'Lowercase u with grave accent',
  },
  {
    character: 'ú',
    entityName: '&uacute;',
    entityNumber: '&#250;',
    description: 'Lowercase u with acute accent',
  },
  {
    character: 'û',
    entityName: '&ucirc;',
    entityNumber: '&#251;',
    description: 'Lowercase u with circumflex accent',
  },
  {
    character: 'ü',
    entityName: '&uuml;',
    entityNumber: '&#252;',
    description: 'Lowercase u with umlaut',
  },
  {
    character: 'ý',
    entityName: '&yacute;',
    entityNumber: '&#253;',
    description: 'Lowercase y with acute accent',
  },
  {
    character: 'þ',
    entityName: '&thorn;',
    entityNumber: '&#254;',
    description: 'Lowercase thorn (Icelandic)',
  },
  {
    character: 'ÿ',
    entityName: '&yuml;',
    entityNumber: '&#255;',
    description: 'Lowercase y with umlaut',
  },
  {
    character: '',
    entityName: '&nbsp;',
    entityNumber: '&#160;',
    description: 'Non-breaking space',
  },
  {
    character: '¡',
    entityName: '&iexcl;',
    entityNumber: '&#161;',
    description: 'Inverted exclamation mark',
  },
  {
    character: '¢',
    entityName: '&cent;',
    entityNumber: '&#162;',
    description: 'Cent',
  },
  {
    character: '£',
    entityName: '&pound;',
    entityNumber: '&#163;',
    description: 'Pound',
  },
  {
    character: '¤',
    entityName: '&curren;',
    entityNumber: '&#164;',
    description: 'Currency',
  },
  {
    character: '¥',
    entityName: '&yen;',
    entityNumber: '&#165;',
    description: 'Yen',
  },
  {
    character: '¦',
    entityName: '&brvbar;',
    entityNumber: '&#166;',
    description: 'Broken vertical bar',
  },
  {
    character: '§',
    entityName: '&sect;',
    entityNumber: '&#167;',
    description: 'Section',
  },
  {
    character: '¨',
    entityName: '&uml;',
    entityNumber: '&#168;',
    description: 'Spacing diaeresis',
  },
  {
    character: '©',
    entityName: '&copy;',
    entityNumber: '&#169;',
    description: 'Copyright',
  },
  {
    character: 'ª',
    entityName: '&ordf;',
    entityNumber: '&#170;',
    description: 'Feminine ordinal indicator',
  },
  {
    character: '«',
    entityName: '&laquo;',
    entityNumber: '&#171;',
    description: 'Opening/Left angle quotation mark',
  },
  {
    character: '¬',
    entityName: '&not;',
    entityNumber: '&#172;',
    description: 'Negation',
  },
  {
    character: '­',
    entityName: '&shy;',
    entityNumber: '&#173;',
    description: 'Soft hyphen',
  },
  {
    character: '®',
    entityName: '&reg;',
    entityNumber: '&#174;',
    description: 'Registered trademark',
  },
  {
    character: '¯',
    entityName: '&macr;',
    entityNumber: '&#175;',
    description: 'Spacing macron',
  },
  {
    character: '°',
    entityName: '&deg;',
    entityNumber: '&#176;',
    description: 'Degree',
  },
  {
    character: '±',
    entityName: '&plusmn;',
    entityNumber: '&#177;',
    description: 'Plus or minus',
  },
  {
    character: '²',
    entityName: '&sup2;',
    entityNumber: '&#178;',
    description: 'Superscript 2',
  },
  {
    character: '³',
    entityName: '&sup3;',
    entityNumber: '&#179;',
    description: 'Superscript 3',
  },
  {
    character: '´',
    entityName: '&acute;',
    entityNumber: '&#180;',
    description: 'Spacing acute',
  },
  {
    character: 'µ',
    entityName: '&micro;',
    entityNumber: '&#181;',
    description: 'Micro',
  },
  {
    character: '¶',
    entityName: '&para;',
    entityNumber: '&#182;',
    description: 'Paragraph',
  },
  {
    character: '¸',
    entityName: '&cedil;',
    entityNumber: '&#184;',
    description: 'Spacing cedilla',
  },
  {
    character: '¹',
    entityName: '&sup1;',
    entityNumber: '&#185;',
    description: 'Superscript 1',
  },
  {
    character: 'º',
    entityName: '&ordm;',
    entityNumber: '&#186;',
    description: 'Masculine ordinal indicator',
  },
  {
    character: '»',
    entityName: '&raquo;',
    entityNumber: '&#187;',
    description: 'Closing/Right angle quotation mark',
  },
  {
    character: '¼',
    entityName: '&frac14;',
    entityNumber: '&#188;',
    description: 'Fraction 1/4',
  },
  {
    character: '½',
    entityName: '&frac12;',
    entityNumber: '&#189;',
    description: 'Fraction 1/2',
  },
  {
    character: '¾',
    entityName: '&frac34;',
    entityNumber: '&#190;',
    description: 'Fraction 3/4',
  },
  {
    character: '¿',
    entityName: '&iquest;',
    entityNumber: '&#191;',
    description: 'Inverted question mark',
  },
  {
    character: '×',
    entityName: '&times;',
    entityNumber: '&#215;',
    description: 'Multiplication',
  },
  {
    character: '÷',
    entityName: '&divide;',
    entityNumber: '&#247;',
    description: 'Divide',
  },
  {
    character: '∀',
    entityName: '&forall;',
    entityNumber: '&#8704;',
    description: 'For all',
  },
  {
    character: '∂',
    entityName: '&part;',
    entityNumber: '&#8706;',
    description: 'Part',
  },
  {
    character: '∃',
    entityName: '&exist;',
    entityNumber: '&#8707;',
    description: 'Exist',
  },
  {
    character: '∅',
    entityName: '&empty;',
    entityNumber: '&#8709;',
    description: 'Empty',
  },
  {
    character: '∇',
    entityName: '&nabla;',
    entityNumber: '&#8711;',
    description: 'Nabla',
  },
  {
    character: '∈',
    entityName: '&isin;',
    entityNumber: '&#8712;',
    description: 'Is in',
  },
  {
    character: '∉',
    entityName: '&notin;',
    entityNumber: '&#8713;',
    description: 'Not in',
  },
  {
    character: '∋',
    entityName: '&ni;',
    entityNumber: '&#8715;',
    description: 'Ni',
  },
  {
    character: '∏',
    entityName: '&prod;',
    entityNumber: '&#8719;',
    description: 'Product',
  },
  {
    character: '∑',
    entityName: '&sum;',
    entityNumber: '&#8721;',
    description: 'Sum',
  },
  {
    character: '−',
    entityName: '&minus;',
    entityNumber: '&#8722;',
    description: 'Minus',
  },
  {
    character: '∗',
    entityName: '&lowast;',
    entityNumber: '&#8727;',
    description: 'Asterisk (Lowast)',
  },
  {
    character: '√',
    entityName: '&radic;',
    entityNumber: '&#8730;',
    description: 'Square root',
  },
  {
    character: '∝',
    entityName: '&prop;',
    entityNumber: '&#8733;',
    description: 'Proportional to',
  },
  {
    character: '∞',
    entityName: '&infin;',
    entityNumber: '&#8734;',
    description: 'Infinity',
  },
  {
    character: '∠',
    entityName: '&ang;',
    entityNumber: '&#8736;',
    description: 'Angle',
  },
  {
    character: '∧',
    entityName: '&and;',
    entityNumber: '&#8743;',
    description: 'And',
  },
  {
    character: '∨',
    entityName: '&or;',
    entityNumber: '&#8744;',
    description: 'Or',
  },
  {
    character: '∩',
    entityName: '&cap;',
    entityNumber: '&#8745;',
    description: 'Cap',
  },
  {
    character: '∪',
    entityName: '&cup;',
    entityNumber: '&#8746;',
    description: 'Cup',
  },
  {
    character: '∫',
    entityName: '&int;',
    entityNumber: '&#8747;',
    description: 'Integral',
  },
  {
    character: '∴',
    entityName: '&there4;',
    entityNumber: '&#8756;',
    description: 'Therefore',
  },
  {
    character: '∼',
    entityName: '&sim;',
    entityNumber: '&#8764;',
    description: 'Similar to',
  },
  {
    character: '≅',
    entityName: '&cong;',
    entityNumber: '&#8773;',
    description: 'Congurent to',
  },
  {
    character: '≈',
    entityName: '&asymp;',
    entityNumber: '&#8776;',
    description: 'Almost equal',
  },
  {
    character: '≠',
    entityName: '&ne;',
    entityNumber: '&#8800;',
    description: 'Not equal',
  },
  {
    character: '≡',
    entityName: '&equiv;',
    entityNumber: '&#8801;',
    description: 'Equivalent',
  },
  {
    character: '≤',
    entityName: '&le;',
    entityNumber: '&#8804;',
    description: 'Less or equal',
  },
  {
    character: '≥',
    entityName: '&ge;',
    entityNumber: '&#8805;',
    description: 'Greater or equal',
  },
  {
    character: '⊂',
    entityName: '&sub;',
    entityNumber: '&#8834;',
    description: 'Subset of',
  },
  {
    character: '⊃',
    entityName: '&sup;',
    entityNumber: '&#8835;',
    description: 'Superset of',
  },
  {
    character: '⊄',
    entityName: '&nsub;',
    entityNumber: '&#8836;',
    description: 'Not subset of',
  },
  {
    character: '⊆',
    entityName: '&sube;',
    entityNumber: '&#8838;',
    description: 'Subset or equal',
  },
  {
    character: '⊇',
    entityName: '&supe;',
    entityNumber: '&#8839;',
    description: 'Superset or equal',
  },
  {
    character: '⊕',
    entityName: '&oplus;',
    entityNumber: '&#8853;',
    description: 'Circled plus',
  },
  {
    character: '⊗',
    entityName: '&otimes;',
    entityNumber: '&#8855;',
    description: 'Circled times',
  },
  {
    character: '⊥',
    entityName: '&perp;',
    entityNumber: '&#8869;',
    description: 'Perpendicular',
  },
  {
    character: '⋅',
    entityName: '&sdot;',
    entityNumber: '&#8901;',
    description: 'Dot operator',
  },
  {
    character: 'Α',
    entityName: '&Alpha;',
    entityNumber: '&#913;',
    description: 'Alpha',
  },
  {
    character: 'Β',
    entityName: '&Beta;',
    entityNumber: '&#914;',
    description: 'Beta',
  },
  {
    character: 'Γ',
    entityName: '&Gamma;',
    entityNumber: '&#915;',
    description: 'Gamma',
  },
  {
    character: 'Δ',
    entityName: '&Delta;',
    entityNumber: '&#916;',
    description: 'Delta',
  },
  {
    character: 'Ε',
    entityName: '&Epsilon;',
    entityNumber: '&#917;',
    description: 'Epsilon',
  },
  {
    character: 'Ζ',
    entityName: '&Zeta;',
    entityNumber: '&#918;',
    description: 'Zeta',
  },
  {
    character: 'Η',
    entityName: '&Eta;',
    entityNumber: '&#919;',
    description: 'Eta',
  },
  {
    character: 'Θ',
    entityName: '&Theta;',
    entityNumber: '&#920;',
    description: 'Theta',
  },
  {
    character: 'Ι',
    entityName: '&Iota;',
    entityNumber: '&#921;',
    description: 'Iota',
  },
  {
    character: 'Κ',
    entityName: '&Kappa;',
    entityNumber: '&#922;',
    description: 'Kappa',
  },
  {
    character: 'Λ',
    entityName: '&Lambda;',
    entityNumber: '&#923;',
    description: 'Lambda',
  },
  {
    character: 'Μ',
    entityName: '&Mu;',
    entityNumber: '&#924;',
    description: 'Mu',
  },
  {
    character: 'Ν',
    entityName: '&Nu;',
    entityNumber: '&#925;',
    description: 'Nu',
  },
  {
    character: 'Ξ',
    entityName: '&Xi;',
    entityNumber: '&#926;',
    description: 'Xi',
  },
  {
    character: 'Ο',
    entityName: '&Omicron;',
    entityNumber: '&#927;',
    description: 'Omicron',
  },
  {
    character: 'Π',
    entityName: '&Pi;',
    entityNumber: '&#928;',
    description: 'Pi',
  },
  {
    character: 'Ρ',
    entityName: '&Rho;',
    entityNumber: '&#929;',
    description: 'Rho',
  },
  {
    character: 'Σ',
    entityName: '&Sigma;',
    entityNumber: '&#931;',
    description: 'Sigma',
  },
  {
    character: 'Τ',
    entityName: '&Tau;',
    entityNumber: '&#932;',
    description: 'Tau',
  },
  {
    character: 'Υ',
    entityName: '&Upsilon;',
    entityNumber: '&#933;',
    description: 'Upsilon',
  },
  {
    character: 'Φ',
    entityName: '&Phi;',
    entityNumber: '&#934;',
    description: 'Phi',
  },
  {
    character: 'Χ',
    entityName: '&Chi;',
    entityNumber: '&#935;',
    description: 'Chi',
  },
  {
    character: 'Ψ',
    entityName: '&Psi;',
    entityNumber: '&#936;',
    description: 'Psi',
  },
  {
    character: 'Ω',
    entityName: '&Omega;',
    entityNumber: '&#937;',
    description: 'Omega',
  },
  {
    character: 'α',
    entityName: '&alpha;',
    entityNumber: '&#945;',
    description: 'alpha',
  },
  {
    character: 'β',
    entityName: '&beta;',
    entityNumber: '&#946;',
    description: 'beta',
  },
  {
    character: 'γ',
    entityName: '&gamma;',
    entityNumber: '&#947;',
    description: 'gamma',
  },
  {
    character: 'δ',
    entityName: '&delta;',
    entityNumber: '&#948;',
    description: 'delta',
  },
  {
    character: 'ε',
    entityName: '&epsilon;',
    entityNumber: '&#949;',
    description: 'epsilon',
  },
  {
    character: 'ζ',
    entityName: '&zeta;',
    entityNumber: '&#950;',
    description: 'zeta',
  },
  {
    character: 'η',
    entityName: '&eta;',
    entityNumber: '&#951;',
    description: 'eta',
  },
  {
    character: 'θ',
    entityName: '&theta;',
    entityNumber: '&#952;',
    description: 'theta',
  },
  {
    character: 'ι',
    entityName: '&iota;',
    entityNumber: '&#953;',
    description: 'iota',
  },
  {
    character: 'κ',
    entityName: '&kappa;',
    entityNumber: '&#954;',
    description: 'kappa',
  },
  {
    character: 'λ',
    entityName: '&lambda;',
    entityNumber: '&#955;',
    description: 'lambda',
  },
  {
    character: 'μ',
    entityName: '&mu;',
    entityNumber: '&#956;',
    description: 'mu',
  },
  {
    character: 'ν',
    entityName: '&nu;',
    entityNumber: '&#957;',
    description: 'nu',
  },
  {
    character: 'ξ',
    entityName: '&xi;',
    entityNumber: '&#958;',
    description: 'xi',
  },
  {
    character: 'ο',
    entityName: '&omicron;',
    entityNumber: '&#959;',
    description: 'omicron',
  },
  {
    character: 'π',
    entityName: '&pi;',
    entityNumber: '&#960;',
    description: 'pi',
  },
  {
    character: 'ρ',
    entityName: '&rho;',
    entityNumber: '&#961;',
    description: 'rho',
  },
  {
    character: 'ς',
    entityName: '&sigmaf;',
    entityNumber: '&#962;',
    description: 'sigmaf',
  },
  {
    character: 'σ',
    entityName: '&sigma;',
    entityNumber: '&#963;',
    description: 'sigma',
  },
  {
    character: 'τ',
    entityName: '&tau;',
    entityNumber: '&#964;',
    description: 'tau',
  },
  {
    character: 'υ',
    entityName: '&upsilon;',
    entityNumber: '&#965;',
    description: 'upsilon',
  },
  {
    character: 'φ',
    entityName: '&phi;',
    entityNumber: '&#966;',
    description: 'phi',
  },
  {
    character: 'χ',
    entityName: '&chi;',
    entityNumber: '&#967;',
    description: 'chi',
  },
  {
    character: 'ψ',
    entityName: '&psi;',
    entityNumber: '&#968;',
    description: 'psi',
  },
  {
    character: 'ω',
    entityName: '&omega;',
    entityNumber: '&#969;',
    description: 'omega',
  },
  {
    character: 'ϑ',
    entityName: '&thetasym;',
    entityNumber: '&#977;',
    description: 'Theta symbol',
  },
  {
    character: 'ϒ',
    entityName: '&upsih;',
    entityNumber: '&#978;',
    description: 'Upsilon symbol',
  },
  {
    character: 'ϖ',
    entityName: '&piv;',
    entityNumber: '&#982;',
    description: 'Pi symbol',
  },
  {
    character: 'Œ',
    entityName: '&OElig;',
    entityNumber: '&#338;',
    description: 'Uppercase ligature OE',
  },
  {
    character: 'œ',
    entityName: '&oelig;',
    entityNumber: '&#339;',
    description: 'Lowercase ligature OE',
  },
  {
    character: 'Š',
    entityName: '&Scaron;',
    entityNumber: '&#352;',
    description: 'Uppercase S with caron',
  },
  {
    character: 'š',
    entityName: '&scaron;',
    entityNumber: '&#353;',
    description: 'Lowercase S with caron',
  },
  {
    character: 'Ÿ',
    entityName: '&Yuml;',
    entityNumber: '&#376;',
    description: 'Capital Y with diaeres',
  },
  {
    character: 'ƒ',
    entityName: '&fnof;',
    entityNumber: '&#402;',
    description: 'Lowercase with hook',
  },
  {
    character: 'ˆ',
    entityName: '&circ;',
    entityNumber: '&#710;',
    description: 'Circumflex accent',
  },
  {
    character: '˜',
    entityName: '&tilde;',
    entityNumber: '&#732;',
    description: 'Tilde',
  },
  {
    character: '',
    entityName: '&ensp;',
    entityNumber: '&#8194;',
    description: 'En space',
  },
  {
    character: '',
    entityName: '&emsp;',
    entityNumber: '&#8195;',
    description: 'Em space',
  },
  {
    character: '',
    entityName: '&thinsp;',
    entityNumber: '&#8201;',
    description: 'Thin space',
  },
  {
    character: '‌',
    entityName: '&zwnj;',
    entityNumber: '&#8204;',
    description: 'Zero width non-joiner',
  },
  {
    character: '‍',
    entityName: '&zwj;',
    entityNumber: '&#8205;',
    description: 'Zero width joiner',
  },
  {
    character: '‎',
    entityName: '&lrm;',
    entityNumber: '&#8206;',
    description: 'Left-to-right mark',
  },
  {
    character: '‏',
    entityName: '&rlm;',
    entityNumber: '&#8207;',
    description: 'Right-to-left mark',
  },
  {
    character: '–',
    entityName: '&ndash;',
    entityNumber: '&#8211;',
    description: 'En dash',
  },
  {
    character: '—',
    entityName: '&mdash;',
    entityNumber: '&#8212;',
    description: 'Em dash',
  },
  {
    character: '‘',
    entityName: '&lsquo;',
    entityNumber: '&#8216;',
    description: 'Left single quotation mark',
  },
  {
    character: '’',
    entityName: '&rsquo;',
    entityNumber: '&#8217;',
    description: 'Right single quotation mark',
  },
  {
    character: '‚',
    entityName: '&sbquo;',
    entityNumber: '&#8218;',
    description: 'Single low-9 quotation mark',
  },
  {
    character: '“',
    entityName: '&ldquo;',
    entityNumber: '&#8220;',
    description: 'Left double quotation mark',
  },
  {
    character: '”',
    entityName: '&rdquo;',
    entityNumber: '&#8221;',
    description: 'Right double quotation mark',
  },
  {
    character: '„',
    entityName: '&bdquo;',
    entityNumber: '&#8222;',
    description: 'Double low-9 quotation mark',
  },
  {
    character: '†',
    entityName: '&dagger;',
    entityNumber: '&#8224;',
    description: 'Dagger',
  },
  {
    character: '‡',
    entityName: '&Dagger;',
    entityNumber: '&#8225;',
    description: 'Double dagger',
  },
  {
    character: '•',
    entityName: '&bull;',
    entityNumber: '&#8226;',
    description: 'Bullet',
  },
  {
    character: '…',
    entityName: '&hellip;',
    entityNumber: '&#8230;',
    description: 'Horizontal ellipsis',
  },
  {
    character: '‰',
    entityName: '&permil;',
    entityNumber: '&#8240;',
    description: 'Per mille',
  },
  {
    character: '′',
    entityName: '&prime;',
    entityNumber: '&#8242;',
    description: 'Minutes (Degrees)',
  },
  {
    character: '″',
    entityName: '&Prime;',
    entityNumber: '&#8243;',
    description: 'Seconds (Degrees)',
  },
  {
    character: '‹',
    entityName: '&lsaquo;',
    entityNumber: '&#8249;',
    description: 'Single left angle quotation',
  },
  {
    character: '›',
    entityName: '&rsaquo;',
    entityNumber: '&#8250;',
    description: 'Single right angle quotation',
  },
  {
    character: '‾',
    entityName: '&oline;',
    entityNumber: '&#8254;',
    description: 'Overline',
  },
  {
    character: '€',
    entityName: '&euro;',
    entityNumber: '&#8364;',
    description: 'Euro',
  },
  {
    character: '™',
    entityName: '&trade;',
    entityNumber: '&#8482;',
    description: 'Trademark',
  },
  {
    character: '←',
    entityName: '&larr;',
    entityNumber: '&#8592;',
    description: 'Left arrow',
  },
  {
    character: '↑',
    entityName: '&uarr;',
    entityNumber: '&#8593;',
    description: 'Up arrow',
  },
  {
    character: '→',
    entityName: '&rarr;',
    entityNumber: '&#8594;',
    description: 'Right arrow',
  },
  {
    character: '↓',
    entityName: '&darr;',
    entityNumber: '&#8595;',
    description: 'Down arrow',
  },
  {
    character: '↔',
    entityName: '&harr;',
    entityNumber: '&#8596;',
    description: 'Left right arrow',
  },
  {
    character: '↵',
    entityName: '&crarr;',
    entityNumber: '&#8629;',
    description: 'Carriage return arrow',
  },
  {
    character: '⌈',
    entityName: '&lceil;',
    entityNumber: '&#8968;',
    description: 'Left ceiling',
  },
  {
    character: '⌉',
    entityName: '&rceil;',
    entityNumber: '&#8969;',
    description: 'Right ceiling',
  },
  {
    character: '⌊',
    entityName: '&lfloor;',
    entityNumber: '&#8970;',
    description: 'Left floor',
  },
  {
    character: '⌋',
    entityName: '&rfloor;',
    entityNumber: '&#8971;',
    description: 'Right floor',
  },
  {
    character: '◊',
    entityName: '&loz;',
    entityNumber: '&#9674;',
    description: 'Lozenge',
  },
  {
    character: '♠',
    entityName: '&spades;',
    entityNumber: '&#9824;',
    description: 'Spade',
  },
  {
    character: '♣',
    entityName: '&clubs;',
    entityNumber: '&#9827;',
    description: 'Club',
  },
  {
    character: '♥',
    entityName: '&hearts;',
    entityNumber: '&#9829;',
    description: 'Heart',
  },
  {
    character: '♦',
    entityName: '&diams;',
    entityNumber: '&#9830;',
    description: 'Diamond',
  },
];

const old = [
  {
    dec: '0',
    hex: '0',
    symbol: 'NUL',
    html_number: '&#0;',
    html_name: '',
    description: 'Null char',
  },
  {
    dec: '1',
    hex: '1',
    symbol: 'SOH',
    html_number: '&#1;',
    html_name: '',
    description: 'Start of heading',
  },
  {
    dec: '2',
    hex: '2',
    symbol: 'STX',
    html_number: '&#2;',
    html_name: '',
    description: 'Start of text',
  },
  {
    dec: '3',
    hex: '3',
    symbol: 'ETX',
    html_number: '&#3;',
    html_name: '',
    description: 'End of text',
  },
  {
    dec: '4',
    hex: '4',
    symbol: 'EOT',
    html_number: '&#4;',
    html_name: '',
    description: 'End of transmission',
  },
  {
    dec: '5',
    hex: '5',
    symbol: 'ENQ',
    html_number: '&#5;',
    html_name: '',
    description: 'Enquiry',
  },
  {
    dec: '6',
    hex: '6',
    symbol: 'ACK',
    html_number: '&#6;',
    html_name: '',
    description: 'Acknowledgment',
  },
  {
    dec: '7',
    hex: '7',
    symbol: 'BEL',
    html_number: '&#7;',
    html_name: '',
    description: 'Bell',
  },
  {
    dec: '8',
    hex: '8',
    symbol: 'BS',
    html_number: '&#8;',
    html_name: '',
    description: 'Backspace',
  },
  {
    dec: '9',
    hex: '9',
    symbol: 'TAB',
    html_number: '&#9;',
    html_name: '',
    description: 'Horizontal tab',
  },
  {
    dec: '10',
    hex: 'A',
    symbol: 'LF',
    html_number: '&#10;',
    html_name: '',
    description: 'Line feed',
  },
  {
    dec: '11',
    hex: 'B',
    symbol: 'VT',
    html_number: '&#11;',
    html_name: '',
    description: 'Vertical tab',
  },
  {
    dec: '12',
    hex: 'C',
    symbol: 'FF',
    html_number: '&#12;',
    html_name: '',
    description: 'Form feed',
  },
  {
    dec: '13',
    hex: 'D',
    symbol: 'CR',
    html_number: '&#13;',
    html_name: '',
    description: 'Carriage return',
  },
  {
    dec: '14',
    hex: 'E',
    symbol: 'SO',
    html_number: '&#14;',
    html_name: '',
    description: 'Shift out / x-on',
  },
  {
    dec: '15',
    hex: 'F',
    symbol: 'SI',
    html_number: '&#15;',
    html_name: '',
    description: 'Shift in / x-off',
  },
  {
    dec: '16',
    hex: '10',
    symbol: 'DLE',
    html_number: '&#16;',
    html_name: '',
    description: 'Data line escape',
  },
  {
    dec: '17',
    hex: '11',
    symbol: 'DC1',
    html_number: '&#17;',
    html_name: '',
    description: 'Device control 1 (oft. xon)',
  },
  {
    dec: '18',
    hex: '12',
    symbol: 'DC2',
    html_number: '&#18;',
    html_name: '',
    description: 'Device control 2',
  },
  {
    dec: '19',
    hex: '13',
    symbol: 'DC3',
    html_number: '&#19;',
    html_name: '',
    description: 'Device control 3 (oft. xoff)',
  },
  {
    dec: '20',
    hex: '14',
    symbol: 'DC4',
    html_number: '&#20;',
    html_name: '',
    description: 'Device control 4',
  },
  {
    dec: '21',
    hex: '15',
    symbol: 'NAK',
    html_number: '&#21;',
    html_name: '',
    description: 'Negative acknowledgement',
  },
  {
    dec: '22',
    hex: '16',
    symbol: 'SYN',
    html_number: '&#22;',
    html_name: '',
    description: 'Synchronous idle',
  },
  {
    dec: '23',
    hex: '17',
    symbol: 'ETB',
    html_number: '&#23;',
    html_name: '',
    description: 'End of transmit block',
  },
  {
    dec: '24',
    hex: '18',
    symbol: 'CAN',
    html_number: '&#24;',
    html_name: '',
    description: 'Cancel',
  },
  {
    dec: '25',
    hex: '19',
    symbol: 'EM',
    html_number: '&#25;',
    html_name: '',
    description: 'End of medium',
  },
  {
    dec: '26',
    hex: '1A',
    symbol: 'SUB',
    html_number: '&#26;',
    html_name: '',
    description: 'Substitute',
  },
  {
    dec: '27',
    hex: '1B',
    symbol: 'ESC',
    html_number: '&#27;',
    html_name: '',
    description: 'Escape',
  },
  {
    dec: '28',
    hex: '1C',
    symbol: 'FS',
    html_number: '&#28;',
    html_name: '',
    description: 'File separator',
  },
  {
    dec: '29',
    hex: '1D',
    symbol: 'GS',
    html_number: '&#29;',
    html_name: '',
    description: 'Group separator',
  },
  {
    dec: '30',
    hex: '1E',
    symbol: 'RS',
    html_number: '&#30;',
    html_name: '',
    description: 'Record separator',
  },
  {
    dec: '31',
    hex: '1F',
    symbol: 'US',
    html_number: '&#31;',
    html_name: '',
    description: 'Unit separator',
  },
  {
    dec: '32',
    hex: '20',
    symbol: '',
    html_number: '&#32;',
    html_name: '',
    description: 'space',
  },
  {
    dec: '33',
    hex: '21',
    symbol: '!',
    html_number: '&#33;',
    html_name: '',
    description: 'exclamation point',
  },
  {
    dec: '34',
    hex: '22',
    symbol: '"',
    html_number: '&#34;',
    html_name: '&quot;',
    description: 'double quotes',
  },
  {
    dec: '35',
    hex: '23',
    symbol: '#',
    html_number: '&#35;',
    html_name: '',
    description: 'number sign',
  },
  {
    dec: '36',
    hex: '24',
    symbol: '$',
    html_number: '&#36;',
    html_name: '',
    description: 'dollar sign',
  },
  {
    dec: '37',
    hex: '25',
    symbol: '%',
    html_number: '&#37;',
    html_name: '',
    description: 'percent sign',
  },
  {
    dec: '38',
    hex: '26',
    symbol: '&',
    html_number: '&#38;',
    html_name: '&amp;',
    description: 'ampersand',
  },
  {
    dec: '39',
    hex: '27',
    symbol: "'",
    html_number: '&#39;',
    html_name: '',
    description: 'single quote',
  },
  {
    dec: '40',
    hex: '28',
    symbol: '(',
    html_number: '&#40;',
    html_name: '',
    description: 'opening parenthesis',
  },
  {
    dec: '41',
    hex: '29',
    symbol: ')',
    html_number: '&#41;',
    html_name: '',
    description: 'closing parenthesis',
  },
  {
    dec: '42',
    hex: '2A',
    symbol: '*',
    html_number: '&#42;',
    html_name: '',
    description: 'asterisk',
  },
  {
    dec: '43',
    hex: '2B',
    symbol: '+',
    html_number: '&#43;',
    html_name: '',
    description: 'plus sign',
  },
  {
    dec: '44',
    hex: '2C',
    symbol: ',',
    html_number: '&#44;',
    html_name: '',
    description: 'comma',
  },
  {
    dec: '45',
    hex: '2D',
    symbol: '-',
    html_number: '&#45;',
    html_name: '',
    description: 'minus sign - hyphen',
  },
  {
    dec: '46',
    hex: '2E',
    symbol: '.',
    html_number: '&#46;',
    html_name: '',
    description: 'period',
  },
  {
    dec: '47',
    hex: '2F',
    symbol: '/',
    html_number: '&#47;',
    html_name: '',
    description: 'slash',
  },
  {
    dec: '48',
    hex: '30',
    symbol: '0',
    html_number: '&#48;',
    html_name: '',
    description: 'zero',
  },
  {
    dec: '49',
    hex: '31',
    symbol: '1',
    html_number: '&#49;',
    html_name: '',
    description: 'one',
  },
  {
    dec: '50',
    hex: '32',
    symbol: '2',
    html_number: '&#50;',
    html_name: '',
    description: 'two',
  },
  {
    dec: '51',
    hex: '33',
    symbol: '3',
    html_number: '&#51;',
    html_name: '',
    description: 'three',
  },
  {
    dec: '52',
    hex: '34',
    symbol: '4',
    html_number: '&#52;',
    html_name: '',
    description: 'four',
  },
  {
    dec: '53',
    hex: '35',
    symbol: '5',
    html_number: '&#53;',
    html_name: '',
    description: 'five',
  },
  {
    dec: '54',
    hex: '36',
    symbol: '6',
    html_number: '&#54;',
    html_name: '',
    description: 'six',
  },
  {
    dec: '55',
    hex: '37',
    symbol: '7',
    html_number: '&#55;',
    html_name: '',
    description: 'seven',
  },
  {
    dec: '56',
    hex: '38',
    symbol: '8',
    html_number: '&#56;',
    html_name: '',
    description: 'eight',
  },
  {
    dec: '57',
    hex: '39',
    symbol: '9',
    html_number: '&#57;',
    html_name: '',
    description: 'nine',
  },
  {
    dec: '58',
    hex: '3A',
    symbol: ':',
    html_number: '&#58;',
    html_name: '',
    description: 'colon',
  },
  {
    dec: '59',
    hex: '3B',
    symbol: ';',
    html_number: '&#59;',
    html_name: '',
    description: 'semicolon',
  },
  {
    dec: '60',
    hex: '3C',
    symbol: '<',
    html_number: '&#60;',
    html_name: '&lt;',
    description: 'less than sign',
  },
  {
    dec: '61',
    hex: '3D',
    symbol: '=',
    html_number: '&#61;',
    html_name: '',
    description: 'equal sign',
  },
  {
    dec: '62',
    hex: '3E',
    symbol: '>',
    html_number: '&#62;',
    html_name: '&gt;',
    description: 'greater than sign',
  },
  {
    dec: '63',
    hex: '3F',
    symbol: '?',
    html_number: '&#63;',
    html_name: '',
    description: 'question mark',
  },
  {
    dec: '64',
    hex: '40',
    symbol: '@',
    html_number: '&#64;',
    html_name: '',
    description: 'at symbol',
  },
  {
    dec: '65',
    hex: '41',
    symbol: 'A',
    html_number: '&#65;',
    html_name: '',
    description: '',
  },
  {
    dec: '66',
    hex: '42',
    symbol: 'B',
    html_number: '&#66;',
    html_name: '',
    description: '',
  },
  {
    dec: '67',
    hex: '43',
    symbol: 'C',
    html_number: '&#67;',
    html_name: '',
    description: '',
  },
  {
    dec: '68',
    hex: '44',
    symbol: 'D',
    html_number: '&#68;',
    html_name: '',
    description: '',
  },
  {
    dec: '69',
    hex: '45',
    symbol: 'E',
    html_number: '&#69;',
    html_name: '',
    description: '',
  },
  {
    dec: '70',
    hex: '46',
    symbol: 'F',
    html_number: '&#70;',
    html_name: '',
    description: '',
  },
  {
    dec: '71',
    hex: '47',
    symbol: 'G',
    html_number: '&#71;',
    html_name: '',
    description: '',
  },
  {
    dec: '72',
    hex: '48',
    symbol: 'H',
    html_number: '&#72;',
    html_name: '',
    description: '',
  },
  {
    dec: '73',
    hex: '49',
    symbol: 'I',
    html_number: '&#73;',
    html_name: '',
    description: '',
  },
  {
    dec: '74',
    hex: '4A',
    symbol: 'J',
    html_number: '&#74;',
    html_name: '',
    description: '',
  },
  {
    dec: '75',
    hex: '4B',
    symbol: 'K',
    html_number: '&#75;',
    html_name: '',
    description: '',
  },
  {
    dec: '76',
    hex: '4C',
    symbol: 'L',
    html_number: '&#76;',
    html_name: '',
    description: '',
  },
  {
    dec: '77',
    hex: '4D',
    symbol: 'M',
    html_number: '&#77;',
    html_name: '',
    description: '',
  },
  {
    dec: '78',
    hex: '4E',
    symbol: 'N',
    html_number: '&#78;',
    html_name: '',
    description: '',
  },
  {
    dec: '79',
    hex: '4F',
    symbol: 'O',
    html_number: '&#79;',
    html_name: '',
    description: '',
  },
  {
    dec: '80',
    hex: '50',
    symbol: 'P',
    html_number: '&#80;',
    html_name: '',
    description: '',
  },
  {
    dec: '81',
    hex: '51',
    symbol: 'Q',
    html_number: '&#81;',
    html_name: '',
    description: '',
  },
  {
    dec: '82',
    hex: '52',
    symbol: 'R',
    html_number: '&#82;',
    html_name: '',
    description: '',
  },
  {
    dec: '83',
    hex: '53',
    symbol: 'S',
    html_number: '&#83;',
    html_name: '',
    description: '',
  },
  {
    dec: '84',
    hex: '54',
    symbol: 'T',
    html_number: '&#84;',
    html_name: '',
    description: '',
  },
  {
    dec: '85',
    hex: '55',
    symbol: 'U',
    html_number: '&#85;',
    html_name: '',
    description: '',
  },
  {
    dec: '86',
    hex: '56',
    symbol: 'V',
    html_number: '&#86;',
    html_name: '',
    description: '',
  },
  {
    dec: '87',
    hex: '57',
    symbol: 'W',
    html_number: '&#87;',
    html_name: '',
    description: '',
  },
  {
    dec: '88',
    hex: '58',
    symbol: 'X',
    html_number: '&#88;',
    html_name: '',
    description: '',
  },
  {
    dec: '89',
    hex: '59',
    symbol: 'Y',
    html_number: '&#89;',
    html_name: '',
    description: '',
  },
  {
    dec: '90',
    hex: '5A',
    symbol: 'Z',
    html_number: '&#90;',
    html_name: '',
    description: '',
  },
  {
    dec: '91',
    hex: '5B',
    symbol: '[',
    html_number: '&#91;',
    html_name: '',
    description: 'opening bracket',
  },
  {
    dec: '92',
    hex: '5C',
    symbol: '\\',
    html_number: '&#92;',
    html_name: '',
    description: 'backslash',
  },
  {
    dec: '93',
    hex: '5D',
    symbol: ']',
    html_number: '&#93;',
    html_name: '',
    description: 'closing bracket',
  },
  {
    dec: '94',
    hex: '5E',
    symbol: '^',
    html_number: '&#94;',
    html_name: '',
    description: 'caret - circumflex',
  },
  {
    dec: '95',
    hex: '5F',
    symbol: '_',
    html_number: '&#95;',
    html_name: '',
    description: 'Underscore',
  },
  {
    dec: '96',
    hex: '60',
    symbol: '`',
    html_number: '&#96;',
    html_name: '',
    description: 'grave accent',
  },
  {
    dec: '97',
    hex: '61',
    symbol: 'a',
    html_number: '&#97;',
    html_name: '',
    description: '',
  },
  {
    dec: '98',
    hex: '62',
    symbol: 'b',
    html_number: '&#98;',
    html_name: '',
    description: '',
  },
  {
    dec: '99',
    hex: '63',
    symbol: 'c',
    html_number: '&#99;',
    html_name: '',
    description: '',
  },
  {
    dec: '100',
    hex: '64',
    symbol: 'd',
    html_number: '&#100;',
    html_name: '',
    description: '',
  },
  {
    dec: '101',
    hex: '65',
    symbol: 'e',
    html_number: '&#101;',
    html_name: '',
    description: '',
  },
  {
    dec: '102',
    hex: '66',
    symbol: 'f',
    html_number: '&#102;',
    html_name: '',
    description: '',
  },
  {
    dec: '103',
    hex: '67',
    symbol: 'g',
    html_number: '&#103;',
    html_name: '',
    description: '',
  },
  {
    dec: '104',
    hex: '68',
    symbol: 'h',
    html_number: '&#104;',
    html_name: '',
    description: '',
  },
  {
    dec: '105',
    hex: '69',
    symbol: 'i',
    html_number: '&#105;',
    html_name: '',
    description: '',
  },
  {
    dec: '106',
    hex: '6A',
    symbol: 'j',
    html_number: '&#106;',
    html_name: '',
    description: '',
  },
  {
    dec: '107',
    hex: '6B',
    symbol: 'k',
    html_number: '&#107;',
    html_name: '',
    description: '',
  },
  {
    dec: '108',
    hex: '6C',
    symbol: 'l',
    html_number: '&#108;',
    html_name: '',
    description: '',
  },
  {
    dec: '109',
    hex: '6D',
    symbol: 'm',
    html_number: '&#109;',
    html_name: '',
    description: '',
  },
  {
    dec: '110',
    hex: '6E',
    symbol: 'n',
    html_number: '&#110;',
    html_name: '',
    description: '',
  },
  {
    dec: '111',
    hex: '6F',
    symbol: 'o',
    html_number: '&#111;',
    html_name: '',
    description: '',
  },
  {
    dec: '112',
    hex: '70',
    symbol: 'p',
    html_number: '&#112;',
    html_name: '',
    description: '',
  },
  {
    dec: '113',
    hex: '71',
    symbol: 'q',
    html_number: '&#113;',
    html_name: '',
    description: '',
  },
  {
    dec: '114',
    hex: '72',
    symbol: 'r',
    html_number: '&#114;',
    html_name: '',
    description: '',
  },
  {
    dec: '115',
    hex: '73',
    symbol: 's',
    html_number: '&#115;',
    html_name: '',
    description: '',
  },
  {
    dec: '116',
    hex: '74',
    symbol: 't',
    html_number: '&#116;',
    html_name: '',
    description: '',
  },
  {
    dec: '117',
    hex: '75',
    symbol: 'u',
    html_number: '&#117;',
    html_name: '',
    description: '',
  },
  {
    dec: '118',
    hex: '76',
    symbol: 'v',
    html_number: '&#118;',
    html_name: '',
    description: '',
  },
  {
    dec: '119',
    hex: '77',
    symbol: 'w',
    html_number: '&#119;',
    html_name: '',
    description: '',
  },
  {
    dec: '120',
    hex: '78',
    symbol: 'x',
    html_number: '&#120;',
    html_name: '',
    description: '',
  },
  {
    dec: '121',
    hex: '79',
    symbol: 'y',
    html_number: '&#121;',
    html_name: '',
    description: '',
  },
  {
    dec: '122',
    hex: '7A',
    symbol: 'z',
    html_number: '&#122;',
    html_name: '',
    description: '',
  },
  {
    dec: '123',
    hex: '7B',
    symbol: '{',
    html_number: '&#123;',
    html_name: '',
    description: 'opening brace',
  },
  {
    dec: '124',
    hex: '7C',
    symbol: '|',
    html_number: '&#124;',
    html_name: '',
    description: 'vertical bar',
  },
  {
    dec: '125',
    hex: '7D',
    symbol: '}',
    html_number: '&#125;',
    html_name: '',
    description: 'closing brace',
  },
  {
    dec: '126',
    hex: '7E',
    symbol: '~',
    html_number: '&#126;',
    html_name: '',
    description: 'equivalency sign - tilde',
  },
  {
    dec: '160',
    hex: 'A0',
    symbol: '',
    html_number: '&#160;',
    html_name: '&nbsp;',
    description: 'non-breaking space',
  },
  {
    dec: '161',
    hex: 'A1',
    symbol: '¡',
    html_number: '&#161;',
    html_name: '&iexcl;',
    description: 'inverted exclamation mark',
  },
  {
    dec: '162',
    hex: 'A2',
    symbol: '¢',
    html_number: '&#162;',
    html_name: '&cent;',
    description: 'cent sign',
  },
  {
    dec: '163',
    hex: 'A3',
    symbol: '£',
    html_number: '&#163;',
    html_name: '&pound;',
    description: 'pound sign',
  },
  {
    dec: '164',
    hex: 'A4',
    symbol: '¤',
    html_number: '&#164;',
    html_name: '&curren;',
    description: 'currency sign',
  },
  {
    dec: '165',
    hex: 'A5',
    symbol: '¥',
    html_number: '&#165;',
    html_name: '&yen;',
    description: 'yen sign',
  },
  {
    dec: '166',
    hex: 'A6',
    symbol: '¦',
    html_number: '&#166;',
    html_name: '&brvbar;',
    description: 'broken vertical bar',
  },
  {
    dec: '167',
    hex: 'A7',
    symbol: '§',
    html_number: '&#167;',
    html_name: '&sect;',
    description: 'section sign',
  },
  {
    dec: '168',
    hex: 'A8',
    symbol: '¨',
    html_number: '&#168;',
    html_name: '&uml;',
    description: 'spacing diaeresis - umlaut',
  },
  {
    dec: '169',
    hex: 'A9',
    symbol: '©',
    html_number: '&#169;',
    html_name: '&copy;',
    description: 'copyright sign',
  },
  {
    dec: '170',
    hex: 'AA',
    symbol: 'ª',
    html_number: '&#170;',
    html_name: '&ordf;',
    description: 'feminine ordinal indicator',
  },
  {
    dec: '171',
    hex: 'AB',
    symbol: '«',
    html_number: '&#171;',
    html_name: '&laquo;',
    description: 'left double angle quotes',
  },
  {
    dec: '172',
    hex: 'AC',
    symbol: '¬',
    html_number: '&#172;',
    html_name: '&not;',
    description: 'not sign',
  },
  {
    dec: '173',
    hex: 'AD',
    symbol: '­',
    html_number: '&#173;',
    html_name: '&shy;',
    description: 'soft hyphen',
  },
  {
    dec: '174',
    hex: 'AE',
    symbol: '®',
    html_number: '&#174;',
    html_name: '&reg;',
    description: 'registered trade mark sign',
  },
  {
    dec: '175',
    hex: 'AF',
    symbol: '¯',
    html_number: '&#175;',
    html_name: '&macr;',
    description: 'spacing macron - overline',
  },
  {
    dec: '176',
    hex: 'B0',
    symbol: '°',
    html_number: '&#176;',
    html_name: '&deg;',
    description: 'degree sign',
  },
  {
    dec: '177',
    hex: 'B1',
    symbol: '±',
    html_number: '&#177;',
    html_name: '&plusmn;',
    description: 'plus-or-minus sign',
  },

  {
    dec: '178',
    hex: 'B2',
    symbol: '²',
    html_number: '&#178;',
    html_name: '&sup2;',
    description: 'superscript two - squared',
  },
  {
    dec: '179',
    hex: 'B3',
    symbol: '³',
    html_number: '&#179;',
    html_name: '&sup3;',
    description: 'superscript three - cubed',
  },
  {
    dec: '180',
    hex: 'B4',
    symbol: '´',
    html_number: '&#180;',
    html_name: '&acute;',
    description: 'acute accent - spacing acute',
  },
  {
    dec: '181',
    hex: 'B5',
    symbol: 'µ',
    html_number: '&#181;',
    html_name: '&micro;',
    description: 'micro sign',
  },
  {
    dec: '182',
    hex: 'B6',
    symbol: '¶',
    html_number: '&#182;',
    html_name: '&para;',
    description: 'pilcrow sign - paragraph sign',
  },
  {
    dec: '183',
    hex: 'B7',
    symbol: '·',
    html_number: '&#183;',
    html_name: '&middot;',
    description: 'middle dot - Georgian comma',
  },
  {
    dec: '184',
    hex: 'B8',
    symbol: '¸',
    html_number: '&#184;',
    html_name: '&cedil;',
    description: 'spacing cedilla',
  },
  {
    dec: '185',
    hex: 'B9',
    symbol: '¹',
    html_number: '&#185;',
    html_name: '&sup1;',
    description: 'superscript one',
  },
  {
    dec: '186',
    hex: 'BA',
    symbol: 'º',
    html_number: '&#186;',
    html_name: '&ordm;',
    description: 'masculine ordinal indicator',
  },
  {
    dec: '187',
    hex: 'BB',
    symbol: '»',
    html_number: '&#187;',
    html_name: '&raquo;',
    description: 'right double angle quotes',
  },
  {
    dec: '188',
    hex: 'BC',
    symbol: '¼',
    html_number: '&#188;',
    html_name: '&frac14;',
    description: 'fraction one quarter',
  },
  {
    dec: '189',
    hex: 'BD',
    symbol: '½',
    html_number: '&#189;',
    html_name: '&frac12;',
    description: 'fraction one half',
  },
  {
    dec: '190',
    hex: 'BE',
    symbol: '¾',
    html_number: '&#190;',
    html_name: '&frac34;',
    description: 'fraction three quarters',
  },
  {
    dec: '191',
    hex: 'BF',
    symbol: '¿',
    html_number: '&#191;',
    html_name: '&iquest;',
    description: 'inverted question mark',
  },
  {
    dec: '192',
    hex: 'C0',
    symbol: 'À',
    html_number: '&#192;',
    html_name: '&Agrave;',
    description: 'latin capital letter A with grave',
  },
  {
    dec: '193',
    hex: 'C1',
    symbol: 'Á',
    html_number: '&#193;',
    html_name: '&Aacute;',
    description: 'latin capital letter A with acute',
  },
  {
    dec: '194',
    hex: 'C2',
    symbol: 'Â',
    html_number: '&#194;',
    html_name: '&Acirc;',
    description: 'latin capital letter A with circumflex',
  },
  {
    dec: '195',
    hex: 'C3',
    symbol: 'Ã',
    html_number: '&#195;',
    html_name: '&Atilde;',
    description: 'latin capital letter A with tilde',
  },
  {
    dec: '196',
    hex: 'C4',
    symbol: 'Ä',
    html_number: '&#196;',
    html_name: '&Auml;',
    description: 'latin capital letter A with diaeresis',
  },
  {
    dec: '197',
    hex: 'C5',
    symbol: 'Å',
    html_number: '&#197;',
    html_name: '&Aring;',
    description: 'latin capital letter A with ring above',
  },
  {
    dec: '198',
    hex: 'C6',
    symbol: 'Æ',
    html_number: '&#198;',
    html_name: '&AElig;',
    description: 'latin capital letter AE',
  },
  {
    dec: '199',
    hex: 'C7',
    symbol: 'Ç',
    html_number: '&#199;',
    html_name: '&Ccedil;',
    description: 'latin capital letter C with cedilla',
  },
  {
    dec: '200',
    hex: 'C8',
    symbol: 'È',
    html_number: '&#200;',
    html_name: '&Egrave;',
    description: 'latin capital letter E with grave',
  },
  {
    dec: '201',
    hex: 'C9',
    symbol: 'É',
    html_number: '&#201;',
    html_name: '&Eacute;',
    description: 'latin capital letter E with acute',
  },
  {
    dec: '202',
    hex: 'CA',
    symbol: 'Ê',
    html_number: '&#202;',
    html_name: '&Ecirc;',
    description: 'latin capital letter E with circumflex',
  },
  {
    dec: '203',
    hex: 'CB',
    symbol: 'Ë',
    html_number: '&#203;',
    html_name: '&Euml;',
    description: 'latin capital letter E with diaeresis',
  },
  {
    dec: '204',
    hex: 'CC',
    symbol: 'Ì',
    html_number: '&#204;',
    html_name: '&Igrave;',
    description: 'latin capital letter I with grave',
  },
  {
    dec: '205',
    hex: 'CD',
    symbol: 'Í',
    html_number: '&#205;',
    html_name: '&Iacute;',
    description: 'latin capital letter I with acute',
  },
  {
    dec: '206',
    hex: 'CE',
    symbol: 'Î',
    html_number: '&#206;',
    html_name: '&Icirc;',
    description: 'latin capital letter I with circumflex',
  },
  {
    dec: '207',
    hex: 'CF',
    symbol: 'Ï',
    html_number: '&#207;',
    html_name: '&Iuml;',
    description: 'latin capital letter I with diaeresis',
  },
  {
    dec: '208',
    hex: 'D0',
    symbol: 'Ð',
    html_number: '&#208;',
    html_name: '&ETH;',
    description: 'latin capital letter ETH',
  },
  {
    dec: '209',
    hex: 'D1',
    symbol: 'Ñ',
    html_number: '&#209;',
    html_name: '&Ntilde;',
    description: 'latin capital letter N with tilde',
  },
  {
    dec: '210',
    hex: 'D2',
    symbol: 'Ò',
    html_number: '&#210;',
    html_name: '&Ograve;',
    description: 'latin capital letter O with grave',
  },
  {
    dec: '211',
    hex: 'D3',
    symbol: 'Ó',
    html_number: '&#211;',
    html_name: '&Oacute;',
    description: 'latin capital letter O with acute',
  },
  {
    dec: '212',
    hex: 'D4',
    symbol: 'Ô',
    html_number: '&#212;',
    html_name: '&Ocirc;',
    description: 'latin capital letter O with circumflex',
  },
  {
    dec: '213',
    hex: 'D5',
    symbol: 'Õ',
    html_number: '&#213;',
    html_name: '&Otilde;',
    description: 'latin capital letter O with tilde',
  },
  {
    dec: '214',
    hex: 'D6',
    symbol: 'Ö',
    html_number: '&#214;',
    html_name: '&Ouml;',
    description: 'latin capital letter O with diaeresis',
  },
  {
    dec: '215',
    hex: 'D7',
    symbol: '×',
    html_number: '&#215;',
    html_name: '&times;',
    description: 'multiplication sign',
  },
  {
    dec: '216',
    hex: 'D8',
    symbol: 'Ø',
    html_number: '&#216;',
    html_name: '&Oslash;',
    description: 'latin capital letter O with slash',
  },
  {
    dec: '217',
    hex: 'D9',
    symbol: 'Ù',
    html_number: '&#217;',
    html_name: '&Ugrave;',
    description: 'latin capital letter U with grave',
  },
  {
    dec: '218',
    hex: 'DA',
    symbol: 'Ú',
    html_number: '&#218;',
    html_name: '&Uacute;',
    description: 'latin capital letter U with acute',
  },
  {
    dec: '219',
    hex: 'DB',
    symbol: 'Û',
    html_number: '&#219;',
    html_name: '&Ucirc;',
    description: 'latin capital letter U with circumflex',
  },
  {
    dec: '220',
    hex: 'DC',
    symbol: 'Ü',
    html_number: '&#220;',
    html_name: '&Uuml;',
    description: 'latin capital letter U with diaeresis',
  },
  {
    dec: '221',
    hex: 'DD',
    symbol: 'Ý',
    html_number: '&#221;',
    html_name: '&Yacute;',
    description: 'latin capital letter Y with acute',
  },
  {
    dec: '222',
    hex: 'DE',
    symbol: 'Þ',
    html_number: '&#222;',
    html_name: '&THORN;',
    description: 'latin capital letter THORN',
  },
  {
    dec: '223',
    hex: 'DF',
    symbol: 'ß',
    html_number: '&#223;',
    html_name: '&szlig;',
    description: 'latin small letter sharp s - ess-zed',
  },
  {
    dec: '224',
    hex: 'E0',
    symbol: 'à',
    html_number: '&#224;',
    html_name: '&agrave;',
    description: 'latin small letter a with grave',
  },
  {
    dec: '225',
    hex: 'E1',
    symbol: 'á',
    html_number: '&#225;',
    html_name: '&aacute;',
    description: 'latin small letter a with acute',
  },
  {
    dec: '226',
    hex: 'E2',
    symbol: 'â',
    html_number: '&#226;',
    html_name: '&acirc;',
    description: 'latin small letter a with circumflex',
  },
  {
    dec: '227',
    hex: 'E3',
    symbol: 'ã',
    html_number: '&#227;',
    html_name: '&atilde;',
    description: 'latin small letter a with tilde',
  },

  {
    dec: '228',
    hex: 'E4',
    symbol: 'ä',
    html_number: '&#228;',
    html_name: '&auml;',
    description: 'latin small letter a with diaeresis',
  },
  {
    dec: '229',
    hex: 'E5',
    symbol: 'å',
    html_number: '&#229;',
    html_name: '&aring;',
    description: 'latin small letter a with ring above',
  },
  {
    dec: '230',
    hex: 'E6',
    symbol: 'æ',
    html_number: '&#230;',
    html_name: '&aelig;',
    description: 'latin small letter ae',
  },
  {
    dec: '231',
    hex: 'E7',
    symbol: 'ç',
    html_number: '&#231;',
    html_name: '&ccedil;',
    description: 'latin small letter c with cedilla',
  },
  {
    dec: '232',
    hex: 'E8',
    symbol: 'è',
    html_number: '&#232;',
    html_name: '&egrave;',
    description: 'latin small letter e with grave',
  },
  {
    dec: '233',
    hex: 'E9',
    symbol: 'é',
    html_number: '&#233;',
    html_name: '&eacute;',
    description: 'latin small letter e with acute',
  },
  {
    dec: '234',
    hex: 'EA',
    symbol: 'ê',
    html_number: '&#234;',
    html_name: '&ecirc;',
    description: 'latin small letter e with circumflex',
  },
  {
    dec: '235',
    hex: 'EB',
    symbol: 'ë',
    html_number: '&#235;',
    html_name: '&euml;',
    description: 'latin small letter e with diaeresis',
  },
  {
    dec: '236',
    hex: 'EC',
    symbol: 'ì',
    html_number: '&#236;',
    html_name: '&igrave;',
    description: 'latin small letter i with grave',
  },
  {
    dec: '237',
    hex: 'ED',
    symbol: 'í',
    html_number: '&#237;',
    html_name: '&iacute;',
    description: 'latin small letter i with acute',
  },
  {
    dec: '238',
    hex: 'EE',
    symbol: 'î',
    html_number: '&#238;',
    html_name: '&icirc;',
    description: 'latin small letter i with circumflex',
  },
  {
    dec: '239',
    hex: 'EF',
    symbol: 'ï',
    html_number: '&#239;',
    html_name: '&iuml;',
    description: 'latin small letter i with diaeresis',
  },
  {
    dec: '240',
    hex: 'F0',
    symbol: 'ð',
    html_number: '&#240;',
    html_name: '&eth;',
    description: 'latin small letter eth',
  },
  {
    dec: '241',
    hex: 'F1',
    symbol: 'ñ',
    html_number: '&#241;',
    html_name: '&ntilde;',
    description: 'latin small letter n with tilde',
  },
  {
    dec: '242',
    hex: 'F2',
    symbol: 'ò',
    html_number: '&#242;',
    html_name: '&ograve;',
    description: 'latin small letter o with grave',
  },
  {
    dec: '243',
    hex: 'F3',
    symbol: 'ó',
    html_number: '&#243;',
    html_name: '&oacute;',
    description: 'latin small letter o with acute',
  },
  {
    dec: '244',
    hex: 'F4',
    symbol: 'ô',
    html_number: '&#244;',
    html_name: '&ocirc;',
    description: 'latin small letter o with circumflex',
  },
  {
    dec: '245',
    hex: 'F5',
    symbol: 'õ',
    html_number: '&#245;',
    html_name: '&otilde;',
    description: 'latin small letter o with tilde',
  },
  {
    dec: '246',
    hex: 'F6',
    symbol: 'ö',
    html_number: '&#246;',
    html_name: '&ouml;',
    description: 'latin small letter o with diaeresis',
  },
  {
    dec: '247',
    hex: 'F7',
    symbol: '÷',
    html_number: '&#247;',
    html_name: '&divide;',
    description: 'division sign',
  },
  {
    dec: '248',
    hex: 'F8',
    symbol: 'ø',
    html_number: '&#248;',
    html_name: '&oslash;',
    description: 'latin small letter o with slash',
  },
  {
    dec: '249',
    hex: 'F9',
    symbol: 'ù',
    html_number: '&#249;',
    html_name: '&ugrave;',
    description: 'latin small letter u with grave',
  },

  {
    dec: '250',
    hex: 'FA',
    symbol: 'ú',
    html_number: '&#250;',
    html_name: '&uacute;',
    description: 'latin small letter u with acute',
  },
  {
    dec: '251',
    hex: 'FB',
    symbol: 'û',
    html_number: '&#251;',
    html_name: '&ucirc;',
    description: 'latin small letter u with circumflex',
  },
  {
    dec: '252',
    hex: 'FC',
    symbol: 'ü',
    html_number: '&#252;',
    html_name: '&uuml;',
    description: 'latin small letter u with diaeresis',
  },
  {
    dec: '253',
    hex: 'FD',
    symbol: 'ý',
    html_number: '&#253;',
    html_name: '&yacute;',
    description: 'latin small letter y with acute',
  },
  {
    dec: '254',
    hex: 'FE',
    symbol: 'þ',
    html_number: '&#254;',
    html_name: '&thorn;',
    description: 'latin small letter thorn',
  },
  {
    dec: '255',
    hex: 'FF',
    symbol: 'ÿ',
    html_number: '&#255;',
    html_name: '&yuml;',
    description: 'latin small letter y with diaeresis',
  },
  {
    dec: '338',
    hex: '152',
    symbol: 'Œ',
    html_number: '&#338;',
    html_name: '',
    description: 'latin capital letter OE',
  },
  {
    dec: '339',
    hex: '153',
    symbol: 'œ',
    html_number: '&#339;',
    html_name: '',
    description: 'latin small letter oe',
  },
  {
    dec: '352',
    hex: '160',
    symbol: 'Š',
    html_number: '&#352;',
    html_name: '',
    description: 'latin capital letter S with caron',
  },
  {
    dec: '353',
    hex: '161',
    symbol: 'š',
    html_number: '&#353;',
    html_name: '',
    description: 'latin small letter s with caron',
  },
  {
    dec: '376',
    hex: '178',
    symbol: 'Ÿ',
    html_number: '&#376;',
    html_name: '',
    description: 'latin capital letter Y with diaeresis',
  },
  {
    dec: '402',
    hex: '192',
    symbol: 'ƒ',
    html_number: '&#402;',
    html_name: '',
    description: 'latin small f with hook - function',
  },
  {
    dec: '8211',
    hex: '2013',
    symbol: '–',
    html_number: '&#8211;',
    html_name: '',
    description: 'en dash',
  },
  {
    dec: '8212',
    hex: '2014',
    symbol: '—',
    html_number: '&#8212;',
    html_name: '',
    description: 'em dash',
  },
  {
    dec: '8216',
    hex: '2018',
    symbol: '‘',
    html_number: '&#8216;',
    html_name: '',
    description: 'left single quotation mark',
  },
  {
    dec: '8217',
    hex: '2019',
    symbol: '’',
    html_number: '&#8217;',
    html_name: '',
    description: 'right single quotation mark',
  },
  {
    dec: '8218',
    hex: '201A',
    symbol: '‚',
    html_number: '&#8218;',
    html_name: '',
    description: 'single low-9 quotation mark',
  },
  {
    dec: '8220',
    hex: '201C',
    symbol: '“',
    html_number: '&#8220;',
    html_name: '',
    description: 'left double quotation mark',
  },
  {
    dec: '8221',
    hex: '201D',
    symbol: '”',
    html_number: '&#8221;',
    html_name: '',
    description: 'right double quotation mark',
  },
  {
    dec: '8222',
    hex: '201E',
    symbol: '„',
    html_number: '&#8222;',
    html_name: '',
    description: 'double low-9 quotation mark',
  },
  {
    dec: '8224',
    hex: '2020',
    symbol: '†',
    html_number: '&#8224;',
    html_name: '',
    description: 'dagger',
  },
  {
    dec: '8225',
    hex: '2021',
    symbol: '‡',
    html_number: '&#8225;',
    html_name: '',
    description: 'double dagger',
  },
  {
    dec: '8226',
    hex: '2022',
    symbol: '•',
    html_number: '&#8226;',
    html_name: '',
    description: 'bullet',
  },
  {
    dec: '8230',
    hex: '2026',
    symbol: '…',
    html_number: '&#8230;',
    html_name: '',
    description: 'horizontal ellipsis',
  },
  {
    dec: '8240',
    hex: '2030',
    symbol: '‰',
    html_number: '&#8240;',
    html_name: '',
    description: 'per thousand sign',
  },
  {
    dec: '8364',
    hex: '20AC',
    symbol: '€',
    html_number: '&#8364;',
    html_name: '&euro;',
    description: 'euro sign',
  },
  {
    dec: '8482',
    hex: '2122',
    symbol: '™',
    html_number: '&#8482;',
    html_name: '',
    description: 'trade mark sign',
  },
];
