import _ from 'lodash';

const continent = [
  {
    code: 'AF',
    name: 'Africa',
    countries: '58',
  },
  {
    code: 'AN',
    name: 'Antartica',
    countries: '5',
  },
  {
    code: 'AS',
    name: 'Asia',
    countries: '53',
  },
  {
    code: 'OC',
    name: 'Oceania',
    countries: '26',
  },
  {
    code: 'EU',
    name: 'Europe',
    countries: '52',
  },
  {
    code: 'NA',
    name: 'North America',
    countries: '41',
  },
  {
    code: 'SA',
    name: 'South America',
    countries: '14',
  },
];

const countryCodes = [
  {
    continent: 'AF',
    name: 'Algeria',
    iso2: 'DZ',
    iso3: 'DZA',
    telephone: '213',
    internet: '.dz',
  },
  {
    continent: 'AF',
    name: 'Angola',
    iso2: 'AO',
    iso3: 'AGO',
    telephone: '244',
    internet: '.ao',
  },
  {
    continent: 'AF',
    name: 'Benin',
    iso2: 'BJ',
    iso3: 'BEN',
    telephone: '229',
    internet: '.bj',
  },
  {
    continent: 'AF',
    name: 'Botswana',
    iso2: 'BW',
    iso3: 'BWA',
    telephone: '267',
    internet: '.bw',
  },
  {
    continent: 'AF',
    name: 'Burkina Faso',
    iso2: 'BF',
    iso3: 'BFA',
    telephone: '226',
    internet: '.bf',
  },
  {
    continent: 'AF',
    name: 'Burundi',
    iso2: 'BI',
    iso3: 'BDI',
    telephone: '257',
    internet: '.bi',
  },
  {
    continent: 'AF',
    name: 'Cameroon',
    iso2: 'CM',
    iso3: 'CMR',
    telephone: '237',
    internet: '.cm',
  },
  {
    continent: 'AF',
    name: 'Cape Verde',
    iso2: 'CV',
    iso3: 'CPV',
    telephone: '238',
    internet: '.cv',
  },
  {
    continent: 'AF',
    name: 'Central African Republic',
    iso2: 'CF',
    iso3: 'CAF',
    telephone: '236',
    internet: '.cf',
  },
  {
    continent: 'AF',
    name: 'Chad',
    iso2: 'TD',
    iso3: 'TCD',
    telephone: '235',
    internet: '.td',
  },
  {
    continent: 'AF',
    name: 'Comoros',
    iso2: 'KM',
    iso3: 'COM',
    telephone: '269',
    internet: '.km',
  },
  {
    continent: 'AF',
    name: 'Congo',
    iso2: 'CG',
    iso3: 'COG',
    telephone: '242',
    internet: '.cg',
  },
  {
    continent: 'AF',
    name: 'Congo, the Democratic Republic of the',
    iso2: 'CD',
    iso3: 'COD',
    telephone: '243',
    internet: '.cd',
  },
  {
    continent: 'AF',
    name: "Côte d'Ivoire",
    iso2: 'CI',
    iso3: 'CIV',
    telephone: '225',
    internet: '.ci',
  },
  {
    continent: 'AF',
    name: 'Djibouti',
    iso2: 'DJ',
    iso3: 'DJI',
    telephone: '253',
    internet: '.dj',
  },
  {
    continent: 'AF',
    name: 'Egypt',
    iso2: 'EG',
    iso3: 'EGY',
    telephone: '20',
    internet: '.eg',
  },
  {
    continent: 'AF',
    name: 'Equatorial Guinea',
    iso2: 'GQ',
    iso3: 'GNQ',
    telephone: '240',
    internet: '.gq',
  },
  {
    continent: 'AF',
    name: 'Eritrea',
    iso2: 'ER',
    iso3: 'ERI',
    telephone: '291',
    internet: '.er',
  },
  {
    continent: 'AF',
    name: 'Ethiopia',
    iso2: 'ET',
    iso3: 'ETH',
    telephone: '251',
    internet: '.et',
  },
  {
    continent: 'AF',
    name: 'Gabon',
    iso2: 'GA',
    iso3: 'GAB',
    telephone: '241',
    internet: '.ga',
  },
  {
    continent: 'AF',
    name: 'Gambia',
    iso2: 'GM',
    iso3: 'GMB',
    telephone: '220',
    internet: '.gm',
  },
  {
    continent: 'AF',
    name: 'Ghana',
    iso2: 'GH',
    iso3: 'GHA',
    telephone: '233',
    internet: '.gh',
  },
  {
    continent: 'AF',
    name: 'Guinea',
    iso2: 'GN',
    iso3: 'GIN',
    telephone: '224',
    internet: '.gn',
  },
  {
    continent: 'AF',
    name: 'Guinea-Bissau',
    iso2: 'GW',
    iso3: 'GNB',
    telephone: '245',
    internet: '.gw',
  },
  {
    continent: 'AF',
    name: 'Kenya',
    iso2: 'KE',
    iso3: 'KEN',
    telephone: '254',
    internet: '.ke',
  },
  {
    continent: 'AF',
    name: 'Lesotho',
    iso2: 'LS',
    iso3: 'LSO',
    telephone: '266',
    internet: '.ls',
  },
  {
    continent: 'AF',
    name: 'Liberia',
    iso2: 'LR',
    iso3: 'LBR',
    telephone: '231',
    internet: '.lr',
  },
  {
    continent: 'AF',
    name: 'Libyan Arab Jamahiriya',
    iso2: 'LY',
    iso3: 'LBY',
    telephone: '218',
    internet: '.ly',
  },
  {
    continent: 'AF',
    name: 'Madagascar',
    iso2: 'MG',
    iso3: 'MDG',
    telephone: '261',
    internet: '.mg',
  },
  {
    continent: 'AF',
    name: 'Malawi',
    iso2: 'MW',
    iso3: 'MWI',
    telephone: '265',
    internet: '.mw',
  },
  {
    continent: 'AF',
    name: 'Mali',
    iso2: 'ML',
    iso3: 'MLI',
    telephone: '223',
    internet: '.ml',
  },
  {
    continent: 'AF',
    name: 'Mauritania',
    iso2: 'MR',
    iso3: 'MRT',
    telephone: '222',
    internet: '.mr',
  },
  {
    continent: 'AF',
    name: 'Mauritius',
    iso2: 'MU',
    iso3: 'MUS',
    telephone: '230',
    internet: '.mu',
  },
  {
    continent: 'AF',
    name: 'Mayotte',
    iso2: 'YT',
    iso3: 'MYT',
    telephone: '262',
    internet: '.yt',
  },
  {
    continent: 'AF',
    name: 'Morocco',
    iso2: 'MA',
    iso3: 'MAR',
    telephone: '212',
    internet: '.ma',
  },
  {
    continent: 'AF',
    name: 'Mozambique',
    iso2: 'MZ',
    iso3: 'MOZ',
    telephone: '258',
    internet: '.mz',
  },
  {
    continent: 'AF',
    name: 'Namibia',
    iso2: 'NA',
    iso3: 'NAM',
    telephone: '264',
    internet: '.na',
  },
  {
    continent: 'AF',
    name: 'Niger',
    iso2: 'NE',
    iso3: 'NER',
    telephone: '227',
    internet: '.ne',
  },
  {
    continent: 'AF',
    name: 'Nigeria',
    iso2: 'NG',
    iso3: 'NGA',
    telephone: '234',
    internet: '.ng',
  },
  {
    continent: 'AF',
    name: 'Réunion',
    iso2: 'RE',
    iso3: 'REU',
    telephone: '262',
    internet: '.re',
  },
  {
    continent: 'AF',
    name: 'Rwanda',
    iso2: 'RW',
    iso3: 'RWA',
    telephone: '250',
    internet: '.rw',
  },
  {
    continent: 'AF',
    name: 'Saint Helena',
    iso2: 'SH',
    iso3: 'SHN',
    telephone: '290',
    internet: '.sh',
  },
  {
    continent: 'AF',
    name: 'Sao Tome and Principe',
    iso2: 'ST',
    iso3: 'STP',
    telephone: '239',
    internet: '.st',
  },
  {
    continent: 'AF',
    name: 'Senegal',
    iso2: 'SN',
    iso3: 'SEN',
    telephone: '221',
    internet: '.sn',
  },
  {
    continent: 'AF',
    name: 'Seychelles',
    iso2: 'SC',
    iso3: 'SYC',
    telephone: '248',
    internet: '.sc',
  },
  {
    continent: 'AF',
    name: 'Sierra Leone',
    iso2: 'SL',
    iso3: 'SLE',
    telephone: '232',
    internet: '.sl',
  },
  {
    continent: 'AF',
    name: 'Somalia',
    iso2: 'SO',
    iso3: 'SOM',
    telephone: '252',
    internet: '.so',
  },
  {
    continent: 'AF',
    name: 'South Africa',
    iso2: 'ZA',
    iso3: 'ZAF',
    telephone: '27',
    internet: '.za',
  },
  {
    continent: 'AF',
    name: 'South Sudan',
    iso2: 'SS',
    iso3: 'SSD',
    telephone: '211',
    internet: '.ss',
  },
  {
    continent: 'AF',
    name: 'Sudan',
    iso2: 'SD',
    iso3: 'SDN',
    telephone: '249',
    internet: '.sd',
  },
  {
    continent: 'AF',
    name: 'Swaziland',
    iso2: 'SZ',
    iso3: 'SWZ',
    telephone: '268',
    internet: '.sz',
  },
  {
    continent: 'AF',
    name: 'Tanzania, United Republic of',
    iso2: 'TZ',
    iso3: 'TZA',
    telephone: '255',
    internet: '.tz',
  },
  {
    continent: 'AF',
    name: 'Togo',
    iso2: 'TG',
    iso3: 'TGO',
    telephone: '228',
    internet: '.tg',
  },
  {
    continent: 'AF',
    name: 'Tunisia',
    iso2: 'TN',
    iso3: 'TUN',
    telephone: '216',
    internet: '.tn',
  },
  {
    continent: 'AF',
    name: 'Uganda',
    iso2: 'UG',
    iso3: 'UGA',
    telephone: '256',
    internet: '.ug',
  },
  {
    continent: 'AF',
    name: 'Western Sahara',
    iso2: 'EH',
    iso3: 'ESH',
    telephone: '212 28',
    internet: '.eh',
  },
  {
    continent: 'AF',
    name: 'Zambia',
    iso2: 'ZM',
    iso3: 'ZMB',
    telephone: '260',
    internet: '.zm',
  },
  {
    continent: 'AF',
    name: 'Zimbabwe',
    iso2: 'ZW',
    iso3: 'ZWE',
    telephone: '263',
    internet: '.zw',
  },
  {
    continent: 'AN',
    name: 'Antarctica',
    iso2: 'AQ',
    iso3: 'ATA',
    telephone: '6721',
    internet: '.aq',
  },
  {
    continent: 'AN',
    name: 'Bouvet Island',
    iso2: 'BV',
    iso3: 'BVT',
    telephone: '47',
    internet: '.bv',
  },
  {
    continent: 'AN',
    name: 'French Southern Territories',
    iso2: 'TF',
    iso3: 'ATF',
    telephone: '-',
    internet: '.tf',
  },
  {
    continent: 'AN',
    name: 'Heard Island and McDonald Islands',
    iso2: 'HM',
    iso3: 'HMD',
    telephone: '1 672',
    internet: '.hm',
  },
  {
    continent: 'AN',
    name: 'South Georgia and the South Sandwich Islands',
    iso2: 'GS',
    iso3: 'SGS',
    telephone: '500',
    internet: '.gs',
  },
  {
    continent: 'AS',
    name: 'Afghanistan',
    iso2: 'AF',
    iso3: 'AFG',
    telephone: '93',
    internet: '.af',
  },
  {
    continent: 'AS',
    name: 'Armenia',
    iso2: 'AM',
    iso3: 'ARM',
    telephone: '374',
    internet: '.am',
  },
  {
    continent: 'AS',
    name: 'Azerbaijan',
    iso2: 'AZ',
    iso3: 'AZE',
    telephone: '994',
    internet: '.az',
  },
  {
    continent: 'AS',
    name: 'Bahrain',
    iso2: 'BH',
    iso3: 'BHR',
    telephone: '973',
    internet: '.bh',
  },
  {
    continent: 'AS',
    name: 'Bangladesh',
    iso2: 'BD',
    iso3: 'BGD',
    telephone: '880',
    internet: '.bd',
  },
  {
    continent: 'AS',
    name: 'Bhutan',
    iso2: 'BT',
    iso3: 'BTN',
    telephone: '975',
    internet: '.bt',
  },
  {
    continent: 'AS',
    name: 'British Indian Ocean Territory',
    iso2: 'IO',
    iso3: 'IOT',
    telephone: '246',
    internet: '.io',
  },
  {
    continent: 'AS',
    name: 'Brunei Darussalam',
    iso2: 'BN',
    iso3: 'BRN',
    telephone: '673',
    internet: '.bn',
  },
  {
    continent: 'AS',
    name: 'Cambodia',
    iso2: 'KH',
    iso3: 'KHM',
    telephone: '855',
    internet: '.kh',
  },
  {
    continent: 'AS',
    name: 'China',
    iso2: 'CN',
    iso3: 'CHN',
    telephone: '86',
    internet: '.cn',
  },
  {
    continent: 'AS',
    name: 'Christmas Island',
    iso2: 'CX',
    iso3: 'CXR',
    telephone: '61',
    internet: '.cx',
  },
  {
    continent: 'AS',
    name: 'Cocos (Keeling) Islands',
    iso2: 'CC',
    iso3: 'CCK',
    telephone: '61',
    internet: '.cc',
  },
  {
    continent: 'AS',
    name: 'Cyprus',
    iso2: 'CY',
    iso3: 'CYP',
    telephone: '357',
    internet: '.cy',
  },
  {
    continent: 'AS',
    name: 'Georgia',
    iso2: 'GE',
    iso3: 'GEO',
    telephone: '995',
    internet: '.ge',
  },
  {
    continent: 'AS',
    name: 'Hong Kong',
    iso2: 'HK',
    iso3: 'HKG',
    telephone: '852',
    internet: '.hk',
  },
  {
    continent: 'AS',
    name: 'India',
    iso2: 'IN',
    iso3: 'IND',
    telephone: '91',
    internet: '.in',
  },
  {
    continent: 'AS',
    name: 'Indonesia',
    iso2: 'ID',
    iso3: 'IDN',
    telephone: '62',
    internet: '.id',
  },
  {
    continent: 'AS',
    name: 'Iran, Islamic Republic of',
    iso2: 'IR',
    iso3: 'IRN',
    telephone: '98',
    internet: '.ir',
  },
  {
    continent: 'AS',
    name: 'Iraq',
    iso2: 'IQ',
    iso3: 'IRQ',
    telephone: '964',
    internet: '.iq',
  },
  {
    continent: 'AS',
    name: 'Israel',
    iso2: 'IL',
    iso3: 'ISR',
    telephone: '972',
    internet: '.il',
  },
  {
    continent: 'AS',
    name: 'Japan',
    iso2: 'JP',
    iso3: 'JPN',
    telephone: '81',
    internet: '.jp',
  },
  {
    continent: 'AS',
    name: 'Jordan',
    iso2: 'JO',
    iso3: 'JOR',
    telephone: '962',
    internet: '.jo',
  },
  {
    continent: 'AS',
    name: 'Kazakhstan',
    iso2: 'KZ',
    iso3: 'KAZ',
    telephone: '7',
    internet: '.kz',
  },
  {
    continent: 'AS',
    name: "Korea, Democratic People's Republic of",
    iso2: 'KP',
    iso3: 'PRK',
    telephone: '850',
    internet: '.kp',
  },
  {
    continent: 'AS',
    name: 'Korea, Republic of',
    iso2: 'KR',
    iso3: 'KOR',
    telephone: '82',
    internet: '.kr',
  },
  {
    continent: 'AS',
    name: 'Kuwait',
    iso2: 'KW',
    iso3: 'KWT',
    telephone: '965',
    internet: '.kw',
  },
  {
    continent: 'AS',
    name: 'Kyrgyzstan',
    iso2: 'KG',
    iso3: 'KGZ',
    telephone: '996',
    internet: '.kg',
  },
  {
    continent: 'AS',
    name: "Lao People's Democratic Republic",
    iso2: 'LA',
    iso3: 'LAO',
    telephone: '856',
    internet: '.la',
  },
  {
    continent: 'AS',
    name: 'Lebanon',
    iso2: 'LB',
    iso3: 'LBN',
    telephone: '961',
    internet: '.lb',
  },
  {
    continent: 'AS',
    name: 'Macao',
    iso2: 'MO',
    iso3: 'MAC',
    telephone: '853',
    internet: '.mo',
  },
  {
    continent: 'AS',
    name: 'Malaysia',
    iso2: 'MY',
    iso3: 'MYS',
    telephone: '60',
    internet: '.my',
  },
  {
    continent: 'AS',
    name: 'Maldives',
    iso2: 'MV',
    iso3: 'MDV',
    telephone: '960',
    internet: '.mv',
  },
  {
    continent: 'AS',
    name: 'Mongolia',
    iso2: 'MN',
    iso3: 'MNG',
    telephone: '976',
    internet: '.mn',
  },
  {
    continent: 'AS',
    name: 'Myanmar',
    iso2: 'MM',
    iso3: 'MMR',
    telephone: '95',
    internet: '.mm',
  },
  {
    continent: 'AS',
    name: 'Nepal',
    iso2: 'NP',
    iso3: 'NPL',
    telephone: '977',
    internet: '.np',
  },
  {
    continent: 'AS',
    name: 'Oman',
    iso2: 'OM',
    iso3: 'OMN',
    telephone: '968',
    internet: '.om',
  },
  {
    continent: 'AS',
    name: 'Pakistan',
    iso2: 'PK',
    iso3: 'PAK',
    telephone: '92',
    internet: '.pk',
  },
  {
    continent: 'AS',
    name: 'Palestinian Territory, Occupied',
    iso2: 'PS',
    iso3: 'PSE',
    telephone: '970',
    internet: '.ps',
  },
  {
    continent: 'AS',
    name: 'Philippines',
    iso2: 'PH',
    iso3: 'PHL',
    telephone: '63',
    internet: '.ph',
  },
  {
    continent: 'AS',
    name: 'Qatar',
    iso2: 'QA',
    iso3: 'QAT',
    telephone: '974',
    internet: '.qa',
  },
  {
    continent: 'AS',
    name: 'Saudi Arabia',
    iso2: 'SA',
    iso3: 'SAU',
    telephone: '966',
    internet: '.sa',
  },
  {
    continent: 'AS',
    name: 'Singapore',
    iso2: 'SG',
    iso3: 'SGP',
    telephone: '65',
    internet: '.sg',
  },
  {
    continent: 'AS',
    name: 'Sri Lanka',
    iso2: 'LK',
    iso3: 'LKA',
    telephone: '94',
    internet: '.lk',
  },
  {
    continent: 'AS',
    name: 'Syrian Arab Republic',
    iso2: 'SY',
    iso3: 'SYR',
    telephone: '963',
    internet: '.sy',
  },
  {
    continent: 'AS',
    name: 'Taiwan, Province of China',
    iso2: 'TW',
    iso3: 'TWN',
    telephone: '886',
    internet: '.tw',
  },
  {
    continent: 'AS',
    name: 'Tajikistan',
    iso2: 'TJ',
    iso3: 'TJK',
    telephone: '992',
    internet: '.tj',
  },
  {
    continent: 'AS',
    name: 'Thailand',
    iso2: 'TH',
    iso3: 'THA',
    telephone: '66',
    internet: '.th',
  },
  {
    continent: 'AS',
    name: 'Timor-Leste',
    iso2: 'TL',
    iso3: 'TLS',
    telephone: '670',
    internet: '.tl',
  },
  {
    continent: 'AS',
    name: 'Turkmenistan',
    iso2: 'TM',
    iso3: 'TKM',
    telephone: '993',
    internet: '.tm',
  },
  {
    continent: 'AS',
    name: 'United Arab Emirates',
    iso2: 'AE',
    iso3: 'ARE',
    telephone: '971',
    internet: '.ae',
  },
  {
    continent: 'AS',
    name: 'Uzbekistan',
    iso2: 'UZ',
    iso3: 'UZB',
    telephone: '998',
    internet: '.uz',
  },
  {
    continent: 'AS',
    name: 'Vietnam',
    iso2: 'VN',
    iso3: 'VNM',
    telephone: '84',
    internet: '.vn',
  },
  {
    continent: 'AS',
    name: 'Yemen',
    iso2: 'YE',
    iso3: 'YEM',
    telephone: '967',
    internet: '.ye',
  },
  {
    continent: 'EU',
    name: 'Åland Islands',
    iso2: 'AX',
    iso3: 'ALA',
    telephone: '358 18',
    internet: '.ax',
  },
  {
    continent: 'EU',
    name: 'Albania',
    iso2: 'AL',
    iso3: 'ALB',
    telephone: '355',
    internet: '.al',
  },
  {
    continent: 'EU',
    name: 'Andorra',
    iso2: 'AD',
    iso3: 'AND',
    telephone: '376',
    internet: '.ad',
  },
  {
    continent: 'EU',
    name: 'Austria',
    iso2: 'AT',
    iso3: 'AUT',
    telephone: '43',
    internet: '.at',
  },
  {
    continent: 'EU',
    name: 'Belarus',
    iso2: 'BY',
    iso3: 'BLR',
    telephone: '375',
    internet: '.by',
  },
  {
    continent: 'EU',
    name: 'Belgium',
    iso2: 'BE',
    iso3: 'BEL',
    telephone: '32',
    internet: '.be',
  },
  {
    continent: 'EU',
    name: 'Bosnia and Herzegovina',
    iso2: 'BA',
    iso3: 'BIH',
    telephone: '387',
    internet: '.ba',
  },
  {
    continent: 'EU',
    name: 'Bulgaria',
    iso2: 'BG',
    iso3: 'BGR',
    telephone: '359',
    internet: '.bg',
  },
  {
    continent: 'EU',
    name: 'Croatia',
    iso2: 'HR',
    iso3: 'HRV',
    telephone: '385',
    internet: '.hr',
  },
  {
    continent: 'EU',
    name: 'Czech Republic',
    iso2: 'CZ',
    iso3: 'CZE',
    telephone: '420',
    internet: '.cz',
  },
  {
    continent: 'EU',
    name: 'Denmark',
    iso2: 'DK',
    iso3: 'DNK',
    telephone: '45',
    internet: '.dk',
  },
  {
    continent: 'EU',
    name: 'Estonia',
    iso2: 'EE',
    iso3: 'EST',
    telephone: '372',
    internet: '.ee',
  },
  {
    continent: 'EU',
    name: 'Faroe Islands',
    iso2: 'FO',
    iso3: 'FRO',
    telephone: '298',
    internet: '.fo',
  },
  {
    continent: 'EU',
    name: 'Finland',
    iso2: 'FI',
    iso3: 'FIN',
    telephone: '358',
    internet: '.fi',
  },
  {
    continent: 'EU',
    name: 'France',
    iso2: 'FR',
    iso3: 'FRA',
    telephone: '33',
    internet: '.fr',
  },
  {
    continent: 'EU',
    name: 'Germany',
    iso2: 'DE',
    iso3: 'DEU',
    telephone: '49',
    internet: '.de',
  },
  {
    continent: 'EU',
    name: 'Gibraltar',
    iso2: 'GI',
    iso3: 'GIB',
    telephone: '350',
    internet: '.gi',
  },
  {
    continent: 'EU',
    name: 'Greece',
    iso2: 'GR',
    iso3: 'GRC',
    telephone: '30',
    internet: '.gr',
  },
  {
    continent: 'EU',
    name: 'Guernsey',
    iso2: 'GG',
    iso3: 'GGY',
    telephone: '44',
    internet: '.gg',
  },
  {
    continent: 'EU',
    name: 'Holy See (Vatican City State)',
    iso2: 'VA',
    iso3: 'VAT',
    telephone: '379',
    internet: '.va',
  },
  {
    continent: 'EU',
    name: 'Hungary',
    iso2: 'HU',
    iso3: 'HUN',
    telephone: '36',
    internet: '.hu',
  },
  {
    continent: 'EU',
    name: 'Iceland',
    iso2: 'IS',
    iso3: 'ISL',
    telephone: '354',
    internet: '.is',
  },
  {
    continent: 'EU',
    name: 'Ireland',
    iso2: 'IE',
    iso3: 'IRL',
    telephone: '353',
    internet: '.ie',
  },
  {
    continent: 'EU',
    name: 'Isle of Man',
    iso2: 'IM',
    iso3: 'IMN',
    telephone: '44',
    internet: '.im',
  },
  {
    continent: 'EU',
    name: 'Italy',
    iso2: 'IT',
    iso3: 'ITA',
    telephone: '39',
    internet: '.it',
  },
  {
    continent: 'EU',
    name: 'Jersey',
    iso2: 'JE',
    iso3: 'JEY',
    telephone: '44',
    internet: '.je',
  },
  {
    continent: 'EU',
    name: 'Latvia',
    iso2: 'LV',
    iso3: 'LVA',
    telephone: '371',
    internet: '.lv',
  },
  {
    continent: 'EU',
    name: 'Liechtenstein',
    iso2: 'LI',
    iso3: 'LIE',
    telephone: '423',
    internet: '.li',
  },
  {
    continent: 'EU',
    name: 'Lithuania',
    iso2: 'LT',
    iso3: 'LTU',
    telephone: '370',
    internet: '.lt',
  },
  {
    continent: 'EU',
    name: 'Luxembourg',
    iso2: 'LU',
    iso3: 'LUX',
    telephone: '352',
    internet: '.lu',
  },
  {
    continent: 'EU',
    name: 'Macedonia, the Former Yugoslav Republic of',
    iso2: 'MK',
    iso3: 'MKD',
    telephone: '389',
    internet: '.mk',
  },
  {
    continent: 'EU',
    name: 'Malta',
    iso2: 'MT',
    iso3: 'MLT',
    telephone: '356',
    internet: '.mt',
  },
  {
    continent: 'EU',
    name: 'Moldova, Republic of',
    iso2: 'MD',
    iso3: 'MDA',
    telephone: '373',
    internet: '.md',
  },
  {
    continent: 'EU',
    name: 'Monaco',
    iso2: 'MC',
    iso3: 'MCO',
    telephone: '377',
    internet: '.mc',
  },
  {
    continent: 'EU',
    name: 'Montenegro',
    iso2: 'ME',
    iso3: 'MNE',
    telephone: '382',
    internet: '.me',
  },
  {
    continent: 'EU',
    name: 'Netherlands',
    iso2: 'NL',
    iso3: 'NLD',
    telephone: '31',
    internet: '.nl',
  },
  {
    continent: 'EU',
    name: 'Norway',
    iso2: 'NO',
    iso3: 'NOR',
    telephone: '47',
    internet: '.no',
  },
  {
    continent: 'EU',
    name: 'Poland',
    iso2: 'PL',
    iso3: 'POL',
    telephone: '48',
    internet: '.pl',
  },
  {
    continent: 'EU',
    name: 'Portugal',
    iso2: 'PT',
    iso3: 'PRT',
    telephone: '351',
    internet: '.pt',
  },
  {
    continent: 'EU',
    name: 'Romania',
    iso2: 'RO',
    iso3: 'ROU',
    telephone: '40',
    internet: '.ro',
  },
  {
    continent: 'EU',
    name: 'Russian Federation',
    iso2: 'RU',
    iso3: 'RUS',
    telephone: '7',
    internet: '.ru',
  },
  {
    continent: 'EU',
    name: 'San Marino',
    iso2: 'SM',
    iso3: 'SMR',
    telephone: '378',
    internet: '.sm',
  },
  {
    continent: 'EU',
    name: 'Serbia',
    iso2: 'RS',
    iso3: 'SRB',
    telephone: '381',
    internet: '.rs',
  },
  {
    continent: 'EU',
    name: 'Slovakia',
    iso2: 'SK',
    iso3: 'SVK',
    telephone: '421',
    internet: '.sk',
  },
  {
    continent: 'EU',
    name: 'Slovenia',
    iso2: 'SI',
    iso3: 'SVN',
    telephone: '386',
    internet: '.si',
  },
  {
    continent: 'EU',
    name: 'Spain',
    iso2: 'ES',
    iso3: 'ESP',
    telephone: '34',
    internet: '.es',
  },
  {
    continent: 'EU',
    name: 'Svalbard and Jan Mayen',
    iso2: 'SJ',
    iso3: 'SJM',
    telephone: '47',
    internet: '.sj',
  },
  {
    continent: 'EU',
    name: 'Sweden',
    iso2: 'SE',
    iso3: 'SWE',
    telephone: '46',
    internet: '.se',
  },
  {
    continent: 'EU',
    name: 'Switzerland',
    iso2: 'CH',
    iso3: 'CHE',
    telephone: '41',
    internet: '.ch',
  },
  {
    continent: 'EU',
    name: 'Turkey',
    iso2: 'TR',
    iso3: 'TUR',
    telephone: '90',
    internet: '.tr',
  },
  {
    continent: 'EU',
    name: 'Ukraine',
    iso2: 'UA',
    iso3: 'UKR',
    telephone: '380',
    internet: '.ua',
  },
  {
    continent: 'EU',
    name: 'United Kingdom',
    iso2: 'GB',
    iso3: 'GBR',
    telephone: '44',
    internet: '.uk',
  },
  {
    continent: 'NA',
    name: 'Anguilla',
    iso2: 'AI',
    iso3: 'AIA',
    telephone: '1 264',
    internet: '.ai',
  },
  {
    continent: 'NA',
    name: 'Antigua and Barbuda',
    iso2: 'AG',
    iso3: 'ATG',
    telephone: '1 268',
    internet: '.ag',
  },
  {
    continent: 'NA',
    name: 'Aruba',
    iso2: 'AW',
    iso3: 'ABW',
    telephone: '297',
    internet: '.aw',
  },
  {
    continent: 'NA',
    name: 'Bahamas',
    iso2: 'BS',
    iso3: 'BHS',
    telephone: '1 242',
    internet: '.bs',
  },
  {
    continent: 'NA',
    name: 'Barbados',
    iso2: 'BB',
    iso3: 'BRB',
    telephone: '1 246',
    internet: '.bb',
  },
  {
    continent: 'NA',
    name: 'Belize',
    iso2: 'BZ',
    iso3: 'BLZ',
    telephone: '501',
    internet: '.bz',
  },
  {
    continent: 'NA',
    name: 'Bermuda',
    iso2: 'BM',
    iso3: 'BMU',
    telephone: '1 441',
    internet: '.bm',
  },
  {
    continent: 'NA',
    name: 'Bonaire, Sint Eustatius and Saba',
    iso2: 'BQ',
    iso3: 'BES',
    telephone: '5997',
    internet: '.bq',
  },
  {
    continent: 'NA',
    name: 'Canada',
    iso2: 'CA',
    iso3: 'CAN',
    telephone: '1',
    internet: '.ca',
  },
  {
    continent: 'NA',
    name: 'Cayman Islands',
    iso2: 'KY',
    iso3: 'CYM',
    telephone: '1 345',
    internet: '.ky',
  },
  {
    continent: 'NA',
    name: 'Costa Rica',
    iso2: 'CR',
    iso3: 'CRI',
    telephone: '506',
    internet: '.cr',
  },
  {
    continent: 'NA',
    name: 'Cuba',
    iso2: 'CU',
    iso3: 'CUB',
    telephone: '53',
    internet: '.cu',
  },
  {
    continent: 'NA',
    name: 'Curaçao',
    iso2: 'CW',
    iso3: 'CUW',
    telephone: '599',
    internet: '.cw',
  },
  {
    continent: 'NA',
    name: 'Dominica',
    iso2: 'DM',
    iso3: 'DMA',
    telephone: '1 767',
    internet: '.dm',
  },
  {
    continent: 'NA',
    name: 'Dominican Republic',
    iso2: 'DO',
    iso3: 'DOM',
    telephone: '1 809/829/ 849',
    internet: '.do',
  },
  {
    continent: 'NA',
    name: 'El Salvador',
    iso2: 'SV',
    iso3: 'SLV',
    telephone: '503',
    internet: '.sv',
  },
  {
    continent: 'NA',
    name: 'Greenland',
    iso2: 'GL',
    iso3: 'GRL',
    telephone: '299',
    internet: '.gl',
  },
  {
    continent: 'NA',
    name: 'Grenada',
    iso2: 'GD',
    iso3: 'GRD',
    telephone: '1 473',
    internet: '.gd',
  },
  {
    continent: 'NA',
    name: 'Guadeloupe',
    iso2: 'GP',
    iso3: 'GLP',
    telephone: '590',
    internet: '.gp',
  },
  {
    continent: 'NA',
    name: 'Guatemala',
    iso2: 'GT',
    iso3: 'GTM',
    telephone: '502',
    internet: '.gt',
  },
  {
    continent: 'NA',
    name: 'Haiti',
    iso2: 'HT',
    iso3: 'HTI',
    telephone: '509',
    internet: '.ht',
  },
  {
    continent: 'NA',
    name: 'Honduras',
    iso2: 'HN',
    iso3: 'HND',
    telephone: '504',
    internet: '.hn',
  },
  {
    continent: 'NA',
    name: 'Jamaica',
    iso2: 'JM',
    iso3: 'JAM',
    telephone: '1 876',
    internet: '.jm',
  },
  {
    continent: 'NA',
    name: 'Martinique',
    iso2: 'MQ',
    iso3: 'MTQ',
    telephone: '596',
    internet: '.mq',
  },
  {
    continent: 'NA',
    name: 'Mexico',
    iso2: 'MX',
    iso3: 'MEX',
    telephone: '52',
    internet: '.mx',
  },
  {
    continent: 'NA',
    name: 'Montserrat',
    iso2: 'MS',
    iso3: 'MSR',
    telephone: '1 664',
    internet: '.ms',
  },
  {
    continent: 'NA',
    name: 'Nicaragua',
    iso2: 'NI',
    iso3: 'NIC',
    telephone: '505',
    internet: '.ni',
  },
  {
    continent: 'NA',
    name: 'Panama',
    iso2: 'PA',
    iso3: 'PAN',
    telephone: '507',
    internet: '.pa',
  },
  {
    continent: 'NA',
    name: 'Puerto Rico',
    iso2: 'PR',
    iso3: 'PRI',
    telephone: '1 787/939',
    internet: '.pr',
  },
  {
    continent: 'NA',
    name: 'Saint Barthélemy',
    iso2: 'BL',
    iso3: 'BLM',
    telephone: '590',
    internet: '.bl',
  },
  {
    continent: 'NA',
    name: 'Saint Kitts and Nevis',
    iso2: 'KN',
    iso3: 'KNA',
    telephone: '1 869',
    internet: '.kn',
  },
  {
    continent: 'NA',
    name: 'Saint Lucia',
    iso2: 'LC',
    iso3: 'LCA',
    telephone: '1 758',
    internet: '.lc',
  },
  {
    continent: 'NA',
    name: 'Saint Martin (French part)',
    iso2: 'MF',
    iso3: 'MAF',
    telephone: '590',
    internet: '.mf',
  },
  {
    continent: 'NA',
    name: 'Saint Pierre and Miquelon',
    iso2: 'PM',
    iso3: 'SPM',
    telephone: '508',
    internet: '.pm',
  },
  {
    continent: 'NA',
    name: 'Saint Vincent and the Grenadines',
    iso2: 'VC',
    iso3: 'VCT',
    telephone: '1 784',
    internet: '.vc',
  },
  {
    continent: 'NA',
    name: 'Sint Maarten (Dutch part)',
    iso2: 'SX',
    iso3: 'SXM',
    telephone: '1 721',
    internet: '.sx',
  },
  {
    continent: 'NA',
    name: 'Trinidad and Tobago',
    iso2: 'TT',
    iso3: 'TTO',
    telephone: '1 868',
    internet: '.tt',
  },
  {
    continent: 'NA',
    name: 'Turks and Caicos Islands',
    iso2: 'TC',
    iso3: 'TCA',
    telephone: '1 649',
    internet: '.tc',
  },
  {
    continent: 'NA',
    name: 'United States',
    iso2: 'US',
    iso3: 'USA',
    telephone: '1',
    internet: '.us',
  },
  {
    continent: 'NA',
    name: 'Virgin Islands, British',
    iso2: 'VG',
    iso3: 'VGB',
    telephone: '1 284',
    internet: '.vg',
  },
  {
    continent: 'NA',
    name: 'Virgin Islands, U.S.',
    iso2: 'VI',
    iso3: 'VIR',
    telephone: '1 340',
    internet: '.vi',
  },
  {
    continent: 'OC',
    name: 'American Samoa',
    iso2: 'AS',
    iso3: 'ASM',
    telephone: '1 684',
    internet: '.as',
  },
  {
    continent: 'OC',
    name: 'Australia',
    iso2: 'AU',
    iso3: 'AUS',
    telephone: '61',
    internet: '.au',
  },
  {
    continent: 'OC',
    name: 'Cook Islands',
    iso2: 'CK',
    iso3: 'COK',
    telephone: '682',
    internet: '.ck',
  },
  {
    continent: 'OC',
    name: 'Fiji',
    iso2: 'FJ',
    iso3: 'FJI',
    telephone: '679',
    internet: '.fj',
  },
  {
    continent: 'OC',
    name: 'French Polynesia',
    iso2: 'PF',
    iso3: 'PYF',
    telephone: '689',
    internet: '.pf',
  },
  {
    continent: 'OC',
    name: 'Guam',
    iso2: 'GU',
    iso3: 'GUM',
    telephone: '1 671',
    internet: '.gu',
  },
  {
    continent: 'OC',
    name: 'Kiribati',
    iso2: 'KI',
    iso3: 'KIR',
    telephone: '686',
    internet: '.ki',
  },
  {
    continent: 'OC',
    name: 'Marshall Islands',
    iso2: 'MH',
    iso3: 'MHL',
    telephone: '692',
    internet: '.mh',
  },
  {
    continent: 'OC',
    name: 'Micronesia, Federated States of',
    iso2: 'FM',
    iso3: 'FSM',
    telephone: '691',
    internet: '.fm',
  },
  {
    continent: 'OC',
    name: 'Nauru',
    iso2: 'NR',
    iso3: 'NRU',
    telephone: '674',
    internet: '.nr',
  },
  {
    continent: 'OC',
    name: 'New Caledonia',
    iso2: 'NC',
    iso3: 'NCL',
    telephone: '687',
    internet: '.nc',
  },
  {
    continent: 'OC',
    name: 'New Zealand',
    iso2: 'NZ',
    iso3: 'NZL',
    telephone: '64',
    internet: '.nz',
  },
  {
    continent: 'OC',
    name: 'Niue',
    iso2: 'NU',
    iso3: 'NIU',
    telephone: '683',
    internet: '.nu',
  },
  {
    continent: 'OC',
    name: 'Norfolk Island',
    iso2: 'NF',
    iso3: 'NFK',
    telephone: '6723',
    internet: '.nf',
  },
  {
    continent: 'OC',
    name: 'Northern Mariana Islands',
    iso2: 'MP',
    iso3: 'MNP',
    telephone: '1 670',
    internet: '.mp',
  },
  {
    continent: 'OC',
    name: 'Palau',
    iso2: 'PW',
    iso3: 'PLW',
    telephone: '680',
    internet: '.pw',
  },
  {
    continent: 'OC',
    name: 'Papua New Guinea',
    iso2: 'PG',
    iso3: 'PNG',
    telephone: '675',
    internet: '.pg',
  },
  {
    continent: 'OC',
    name: 'Pitcairn',
    iso2: 'PN',
    iso3: 'PCN',
    telephone: '64',
    internet: '.pn',
  },
  {
    continent: 'OC',
    name: 'Samoa',
    iso2: 'WS',
    iso3: 'WSM',
    telephone: '685',
    internet: '.ws',
  },
  {
    continent: 'OC',
    name: 'Solomon Islands',
    iso2: 'SB',
    iso3: 'SLB',
    telephone: '677',
    internet: '.sb',
  },
  {
    continent: 'OC',
    name: 'Tokelau',
    iso2: 'TK',
    iso3: 'TKL',
    telephone: '690',
    internet: '.tk',
  },
  {
    continent: 'OC',
    name: 'Tonga',
    iso2: 'TO',
    iso3: 'TON',
    telephone: '676',
    internet: '.to',
  },
  {
    continent: 'OC',
    name: 'Tuvalu',
    iso2: 'TV',
    iso3: 'TUV',
    telephone: '688',
    internet: '.tv',
  },
  {
    continent: 'OC',
    name: 'United States Minor Outlying Islands',
    iso2: 'UM',
    iso3: 'UMI',
    telephone: '1 808',
    internet: '.um',
  },
  {
    continent: 'OC',
    name: 'Vanuatu',
    iso2: 'VU',
    iso3: 'VUT',
    telephone: '678',
    internet: '.vu',
  },
  {
    continent: 'OC',
    name: 'Wallis and Futuna',
    iso2: 'WF',
    iso3: 'WLF',
    telephone: '681',
    internet: '.wf',
  },
  {
    continent: 'SA',
    name: 'Argentina',
    iso2: 'AR',
    iso3: 'ARG',
    telephone: '54',
    internet: '.ar',
  },
  {
    continent: 'SA',
    name: 'Bolivia',
    iso2: 'BO',
    iso3: 'BOL',
    telephone: '591',
    internet: '.bo',
  },
  {
    continent: 'SA',
    name: 'Brazil',
    iso2: 'BR',
    iso3: 'BRA',
    telephone: '55',
    internet: '.br',
  },
  {
    continent: 'SA',
    name: 'Chile',
    iso2: 'CL',
    iso3: 'CHL',
    telephone: '56',
    internet: '.cl',
  },
  {
    continent: 'SA',
    name: 'Colombia',
    iso2: 'CO',
    iso3: 'COL',
    telephone: '57',
    internet: '.co',
  },
  {
    continent: 'SA',
    name: 'Ecuador',
    iso2: 'EC',
    iso3: 'ECU',
    telephone: '593',
    internet: '.ec',
  },
  {
    continent: 'SA',
    name: 'Falkland Islands (Malvinas)',
    iso2: 'FK',
    iso3: 'FLK',
    telephone: '500',
    internet: '.fk',
  },
  {
    continent: 'SA',
    name: 'French Guiana',
    iso2: 'GF',
    iso3: 'GUF',
    telephone: '594',
    internet: '.gf',
  },
  {
    continent: 'SA',
    name: 'Guyana',
    iso2: 'GY',
    iso3: 'GUY',
    telephone: '592',
    internet: '.gy',
  },
  {
    continent: 'SA',
    name: 'Paraguay',
    iso2: 'PY',
    iso3: 'PRY',
    telephone: '595',
    internet: '.py',
  },
  {
    continent: 'SA',
    name: 'Peru',
    iso2: 'PE',
    iso3: 'PER',
    telephone: '51',
    internet: '.pe',
  },
  {
    continent: 'SA',
    name: 'Suriname',
    iso2: 'SR',
    iso3: 'SUR',
    telephone: '597',
    internet: '.sr',
  },
  {
    continent: 'SA',
    name: 'Uruguay',
    iso2: 'UY',
    iso3: 'URY',
    telephone: '598',
    internet: '.uy',
  },
  {
    continent: 'SA',
    name: 'Venezuela',
    iso2: 'VE',
    iso3: 'VEN',
    telephone: '58',
    internet: '.ve',
  },
];

const search = (kw) => {
  const patt = new RegExp(kw, 'i');
  return _.filter(
    countryCodes,
    (p) =>
      patt.test(p.continent) ||
      patt.test(p.name) ||
      patt.test(p.iso2) ||
      patt.test(p.iso3) ||
      patt.test(p.telephone) ||
      patt.test(p.internet)
  );
};

export { continent, countryCodes, search };
